# -*- coding: utf-8 -*-
"""pfefmz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJkzDeRZGjyz9mhPZYWgcHrtI2LZjcJF
"""

5# ============================================================
# PFEFM — ENTRAÎNEMENT COMPLET
# Notebook Google Colab — Version finale (pfe )
# ============================================================

# ── CELLULE 1 : Installation ──────────────────────────────────
!pip install xgboost lightgbm shap --quiet

# ── CELLULE 2 : Imports ───────────────────────────────────────
import os, json, joblib, warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
warnings.filterwarnings("ignore")
from google.colab import drive

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score,
    roc_curve, average_precision_score, precision_recall_curve,
    ConfusionMatrixDisplay
)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# ── CELLULE 3 : Google Drive + chargement ────────────────────
drive.mount('/content/drive')
OUTPUT_PATH = '/content/drive/MyDrive/pfefmz/'
os.makedirs(OUTPUT_PATH, exist_ok=True)
TODAY = pd.Timestamp("2026-03-30")

df = pd.read_parquet(OUTPUT_PATH + 'enterprises_clean.parquet')
print(f"Dataset : {df.shape[0]:,} lignes x {df.shape[1]} colonnes")

# ── CELLULE 4 : Séparation des segments ──────────────────────
df_morale   = df[df["typePersonneContent"].str.strip() == "morale"].copy().reset_index(drop=True)
df_physique = df[df["typePersonneContent"].str.strip() == "physique"].copy().reset_index(drop=True)

print(f"Morale   : {len(df_morale):,} | Cessées : {(df_morale['est_active']==0).sum():,}")
print(f"Physique : {len(df_physique):,} | Cessées : {(df_physique['est_active']==0).sum():,}")

# ── CELLULE 5 : Feature Engineering ─────────────────────────
def build_features(df_in):
    df = df_in.copy()

    # Rôle judiciaire du dirigeant
    codes_judiciaires = ["60","65","70","71","72","73","74","75"]
    df["dirigeant_role_str"] = df["dirigeant_role"].fillna("").astype(str).str.strip()
    df["dirigeant_est_judiciaire"]  = df["dirigeant_role_str"].isin(codes_judiciaires).astype(int)
    df["dirigeant_est_liquidateur"] = (df["dirigeant_role_str"] == "73").astype(int)
    df["dirigeant_est_mandataire"]  = (df["dirigeant_role_str"] == "65").astype(int)

    # Age du dirigeant
    def parse_annee(ddn):
        try:
            s = str(ddn).strip()
            if len(s) >= 4 and s[:4].isdigit():
                return int(s[:4])
        except:
            pass
        return np.nan

    df["dirigeant_age"] = df["dirigeant_ddn"].apply(parse_annee)
    df["dirigeant_age"] = 2026 - df["dirigeant_age"]
    df["dirigeant_age"] = df["dirigeant_age"].where(df["dirigeant_age"].between(18,100), np.nan)
    df["dirigeant_age_risque"] = np.where(
        df["dirigeant_age"].isna(), 0,
        ((df["dirigeant_age"] < 25) | (df["dirigeant_age"] > 70)).astype(int)
    )

    # Capital
    capital = pd.to_numeric(df["identite.montantCapital"], errors="coerce")
    df["capital_symbolique"]  = (capital == 1).astype(int)
    df["capital_tres_faible"] = capital.between(0, 1000, inclusive="both").astype(int)
    df["capital_absent"]      = capital.isna().astype(int)

    # Représentants
    nb_rep = pd.to_numeric(df["nombreRepresentantsActifs"], errors="coerce").fillna(0)
    df["pas_representant_actif"] = (nb_rep == 0).astype(int)

    # Dépôt obligatoire non respecté
    formes_obligatoires = ["5499","5710","5720","5599","5531","5560","5498","5308"]
    fj         = df["identite.formeJuridique"].fillna("").astype(str).str.strip()
    age_num    = pd.to_numeric(df["age_ans"], errors="coerce").fillna(0)
    nb_ann     = pd.to_numeric(df.get("nb_annonces_bodacc",  pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    flag_depot = pd.to_numeric(df.get("flag_depot_comptes",  pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    df["depot_non_respecte"] = (
        fj.isin(formes_obligatoires) & (flag_depot == 0) & (age_num > 2)
    ).astype(int)

    # Fréquences
    df["frequence_bodacc"] = np.where(age_num > 0, (nb_ann / age_num).round(4), 0.0)

    nb_etab_ouv = pd.to_numeric(df.get("nombreEtablissementsOuverts", pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    nb_obs      = pd.to_numeric(df.get("nb_observations",             pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    taux        = pd.to_numeric(df.get("taux_cessation_sectoriel",    pd.Series(0, index=df.index)), errors="coerce").fillna(0)

    df["frequence_observations"] = np.where(age_num > 0, (nb_obs / age_num).round(4), 0.0)
    df["jeune_secteur_risque"]   = ((age_num < 3) & (taux > taux.mean())).astype(int)
    df["ancienne_inactive"]      = ((age_num > 20) & (nb_ann == 0) & (nb_etab_ouv == 0)).astype(int)

    est_micro = df.get("est_micro", pd.Series(0, index=df.index)).fillna(0).astype(int)
    df["micro_sans_capital"] = ((est_micro == 1) & (capital.isna() | (capital == 0))).astype(int)

    return df

df_morale   = build_features(df_morale)
df_physique = build_features(df_physique)
print("Features construites.")

# ── CELLULE 6 : Split temporel ───────────────────────────────
print("\n[Split temporel]")
df_morale["date_radiation"] = pd.to_datetime(
    df_morale["cessation.dateRadiation"], errors="coerce"
)

CUTOFF = pd.Timestamp("2023-01-01")

cessees_train     = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"] <  CUTOFF)]
cessees_test      = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"] >= CUTOFF)]
cessees_sans_date = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"].isna())]
actives           = df_morale[ df_morale["est_active"]==1]

ratio_split     = len(cessees_train) / max(len(cessees_train)+len(cessees_test), 1)
n_actives_train = int(len(actives) * ratio_split)

actives_shuffled = actives.sample(frac=1, random_state=42)
actives_train    = actives_shuffled.iloc[:n_actives_train]
actives_test     = actives_shuffled.iloc[n_actives_train:]

df_train = pd.concat([cessees_train, cessees_sans_date, actives_train], ignore_index=True)
df_test  = pd.concat([cessees_test,  actives_test],                     ignore_index=True)

print(f"Train : {len(df_train):,} lignes | {(df_train['est_active']==0).sum()} cessées")
print(f"Test  : {len(df_test):,}  lignes | {(df_test['est_active']==0).sum()} cessées (2023 jamais vues)")

# ── CELLULE 7 : Features ML ──────────────────────────────────
# Features leakage supprimées — reflètent état POST-cessation
FEATURES_LEAKAGE = [
    "pas_representant_actif",       # dirigeants radiés après cessation
    "capital_absent",               # capital effacé après cessation
    "nombreRepresentantsActifs",    # tombe à 0 après cessation
    "nombreEtablissementsOuverts",  # ferme lors de la cessation
    "jours_depuis_bodacc",          # dernière annonce = acte de dissolution
    "flag_cession_bodacc",          # annonce de cession = cessation
]

FEATURES_NUM = [
    "age_ans", "jours_depuis_update",
    "nb_etab_secondaires", "nb_etab_fermes", "nb_representants_extraits",
    "log_capital", "capital_symbolique", "capital_tres_faible",
    "nb_annonces_bodacc", "flag_procedure_collective",
    "flag_creation_bodacc", "flag_depot_comptes", "flag_modification_bodacc",
    "frequence_bodacc",
    "nb_observations", "nb_observations_critiques", "has_alerte_juridique",
    "frequence_observations",
    "dirigeant_est_judiciaire", "dirigeant_est_liquidateur", "dirigeant_est_mandataire",
    "dirigeant_age", "dirigeant_age_risque",
    "depot_non_respecte",
    "est_ess", "est_micro", "est_eirl", "est_agricole", "est_etranger",
    "multi_etablissement", "diffusion_insee", "micro_sans_capital",
    "taux_cessation_sectoriel", "age_median_sectoriel",
    "jeune_secteur_risque", "ancienne_inactive",
    "has_bilan", "bilan_chiffre_affaires", "bilan_resultat_net",
    "bilan_capitaux_propres", "bilan_total_actif",
    "bilan_marge_nette", "bilan_capitaux_negatifs",
]
FEATURES_CAT = [
    "forme_juridique_lib", "secteur_naf2", "stade_vie",
    "forme_juridique_risque", "departement",
]
FEATURES_NUM = [f for f in FEATURES_NUM if f in df_morale.columns]
FEATURES_CAT = [f for f in FEATURES_CAT if f in df_morale.columns]

print(f"Features ML : {len(FEATURES_NUM)+len(FEATURES_CAT)} | Leakage supprimé : {len(FEATURES_LEAKAGE)}")

# ── CELLULE 8 : Préparation des données ──────────────────────
def prepare_X(df_in, le_dict, fit=False):
    X = df_in[FEATURES_NUM + FEATURES_CAT].copy()
    for col in FEATURES_CAT:
        X[col] = X[col].fillna("Inconnu").astype(str)
        if fit:
            # Forcer "Inconnu" dans les classes pour gérer les valeurs inconnues au test
            all_vals = list(X[col].unique()) + ["Inconnu"]
            le = LabelEncoder()
            le.fit(all_vals)
            X[col] = le.transform(X[col])
            le_dict[col] = le
        else:
            X[col] = le_dict[col].transform(
                X[col].map(lambda x: x if x in le_dict[col].classes_ else "Inconnu")
            )
    for col in FEATURES_NUM:
        X[col] = pd.to_numeric(X[col], errors="coerce")
    return X


le_dict = {}
X_train = prepare_X(df_train, le_dict, fit=True)
y_train = df_train["est_active"].astype(int)
X_test  = prepare_X(df_test,  le_dict, fit=False)
y_test  = df_test["est_active"].astype(int)

ratio = (y_train==0).sum() / (y_train==1).sum()
print(f"Ratio cessées/actives : {ratio:.3f}")

# ── CELLULE 9 : Modèle 1 — XGBoost ──────────────────────────
print("\n" + "="*60)
print("  MODELE 1 — XGBOOST — VALIDATION TEMPORELLE")
print("="*60)

cv      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring = ["roc_auc","f1","recall"]

xgb_model = XGBClassifier(
    n_estimators=500, max_depth=6, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8,
    scale_pos_weight=ratio, eval_metric="logloss",
    random_state=42, n_jobs=-1,
)
lgbm_model = LGBMClassifier(
    n_estimators=500, max_depth=6, learning_rate=0.05,
    subsample=0.8, colsample_bytree=0.8,
    class_weight="balanced", random_state=42, n_jobs=-1, verbose=-1,
)

cv_results = {}
for name, model in [("XGBoost", xgb_model), ("LightGBM", lgbm_model)]:
    scores = cross_validate(model, X_train, y_train, cv=cv, scoring=scoring, n_jobs=-1)
    cv_results[name] = scores
    print(f"\n{name} (CV sur train) :")
    print(f"  ROC-AUC : {scores['test_roc_auc'].mean():.4f} +/- {scores['test_roc_auc'].std():.4f}")
    print(f"  F1      : {scores['test_f1'].mean():.4f} | Recall : {scores['test_recall'].mean():.4f}")

xgb_model.fit(X_train, y_train)
lgbm_model.fit(X_train, y_train)

y_prob = xgb_model.predict_proba(X_test)[:,1]
y_pred = xgb_model.predict(X_test)

print(f"\nXGBoost Test ROC-AUC : {roc_auc_score(y_test, y_prob):.4f}")
print(classification_report(y_test, y_pred, target_names=["Cessée","Active"]))

mask_cess = df_test["est_active"]==0
n_det = (y_pred[mask_cess]==0).sum()
n_tot = mask_cess.sum()
print(f"Cessées 2023 détectées : {n_det}/{n_tot} ({n_det/n_tot*100:.1f}%)")

# ── CELLULE 10 : Modèle 2 — Score physique ───────────────────
print("\n" + "="*60)
print("  MODELE 2 — SCORE REGLES METIER — PHYSIQUE")
print("="*60)

def score_physique(row):
    score = 60.0
    score -= row.get("flag_procedure_collective",    0) * 40
    score -= row.get("has_alerte_juridique",          0) * 30
    score -= row.get("dirigeant_est_judiciaire",      0) * 25
    score -= row.get("dirigeant_est_liquidateur",     0) * 15
    score -= row.get("depot_non_respecte",            0) * 10
    score -= row.get("pas_representant_actif",        0) * 10   # valide ici (pas de ML)
    score -= min(row.get("nb_annonces_bodacc",        0) * 2, 10)
    score -= min(row.get("nb_observations_critiques", 0) * 5, 20)
    score -= row.get("capital_absent",                0) * 5    # valide ici (pas de ML)
    score -= row.get("capital_tres_faible",           0) * 3
    taux = row.get("taux_cessation_sectoriel", 0.068) or 0.068
    score -= min(max(0, (taux/0.068 - 1) * 5), 10)
    return round(max(0, min(100, score)), 2)

def niveau_risque(score):
    if score >= 65: return "Faible"
    if score >= 45: return "Modéré"
    if score >= 25: return "Élevé"
    return "Critique"

df_physique["score_risque_physique"] = df_physique.apply(score_physique, axis=1)
df_physique["niveau_risque"]         = df_physique["score_risque_physique"].apply(niveau_risque)

print(f"\nDistribution :")
print(df_physique["niveau_risque"].value_counts())
print(f"Score moyen : {df_physique['score_risque_physique'].mean():.1f}")

# ── CELLULE 11 : Modèle 3 — Isolation Forest ─────────────────
print("\n" + "="*60)
print("  MODELE 3 — ISOLATION FOREST — TOUS")
print("="*60)

FEATURES_IF = [f for f in [
    "age_ans", "log_capital",
    "nb_annonces_bodacc", "flag_procedure_collective",
    "has_alerte_juridique", "nb_observations_critiques",
    "dirigeant_est_judiciaire", "frequence_bodacc",
    "taux_cessation_sectoriel", "depot_non_respecte",
] if f in df_morale.columns]

X_actives = df_morale[df_morale["est_active"]==1][FEATURES_IF].copy()
for col in FEATURES_IF:
    X_actives[col] = pd.to_numeric(X_actives[col], errors="coerce").fillna(0)

iso_forest = IsolationForest(n_estimators=200, contamination=0.05, random_state=42, n_jobs=-1)
iso_forest.fit(X_actives)
print(f"Entraîné sur {len(X_actives):,} actives")

df_full   = pd.concat([df_morale, df_physique], ignore_index=True)
X_if_full = df_full[FEATURES_IF].copy()
for col in FEATURES_IF:
    X_if_full[col] = pd.to_numeric(X_if_full[col], errors="coerce").fillna(0)

df_full["anomalie_score"] = iso_forest.decision_function(X_if_full).round(4)
df_full["est_anomalie"]   = (iso_forest.predict(X_if_full)==-1).astype(int)
print(f"Anomalies détectées : {df_full['est_anomalie'].sum():,} / {len(df_full):,}")

# ── CELLULE 12 : Prédictions finales ─────────────────────────
print("\nPrédictions finales...")

X_full_morale = prepare_X(df_morale, le_dict, fit=False)
df_morale["proba_cessee"]         = xgb_model.predict_proba(X_full_morale)[:,0].round(4)
df_morale["proba_active"]         = xgb_model.predict_proba(X_full_morale)[:,1].round(4)
df_morale["prediction_ml"]        = xgb_model.predict(X_full_morale)
df_morale["score_confiance"]      = df_morale[["proba_active","proba_cessee"]].max(axis=1).round(4)
df_morale["modele_utilise"]       = "XGBoost"

def cat_morale(p):
    if p >= 0.75: return "Risque très élevé"
    if p >= 0.50: return "Risque élevé"
    if p >= 0.30: return "Risque modéré"
    return "Faible risque"

df_morale["categorie_prediction"] = df_morale["proba_cessee"].apply(cat_morale)

df_physique["proba_cessee"]         = np.nan
df_physique["proba_active"]         = np.nan
df_physique["prediction_ml"]        = np.nan
df_physique["score_confiance"]      = np.nan
df_physique["modele_utilise"]       = "Score_Règles"
df_physique["categorie_prediction"] = df_physique["niveau_risque"].map({
    "Critique": "Risque très élevé",
    "Élevé":    "Risque élevé",
    "Modéré":   "Risque modéré",
    "Faible":   "Faible risque",
})

cess_det = (df_morale[df_morale["est_active"]==0]["prediction_ml"]==0).sum()
cess_tot = (df_morale["est_active"]==0).sum()
print(f"[Morale]   Cessées détectées : {cess_det}/{cess_tot} ({cess_det/cess_tot*100:.1f}%)")
print(f"[Physique] Risque élevé+critique : {(df_physique['niveau_risque'].isin(['Élevé','Critique'])).sum()}")

# ── CELLULE 13 : Graphiques ───────────────────────────────────
# Matrice + ROC + PR
fig, axes = plt.subplots(1, 3, figsize=(18,5))

cm_val = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm_val, display_labels=["Cessée","Active"]).plot(ax=axes[0], colorbar=False)
axes[0].set_title("Matrice confusion — Test temporel 2023")

fpr, tpr, _ = roc_curve(y_test, y_prob)
axes[1].plot(fpr, tpr, label=f"AUC={roc_auc_score(y_test,y_prob):.4f}", color="steelblue", lw=2)
axes[1].plot([0,1],[0,1],"--", color="gray")
axes[1].set(title="Courbe ROC — Test temporel", xlabel="Faux positifs", ylabel="Vrais positifs")
axes[1].legend()

prec, rec, _ = precision_recall_curve(y_test, y_prob)
axes[2].plot(rec, prec, label=f"AP={average_precision_score(y_test,y_prob):.4f}", color="coral", lw=2)
axes[2].set(title="Precision-Recall", xlabel="Recall", ylabel="Precision")
axes[2].legend()

plt.tight_layout()
plt.savefig(OUTPUT_PATH+"evaluation_temporelle.png", dpi=150, bbox_inches="tight")
plt.show()

# Feature importance
fig, ax = plt.subplots(figsize=(10,10))
pd.Series(xgb_model.feature_importances_, index=FEATURES_NUM+FEATURES_CAT) \
  .sort_values(ascending=True).tail(30) \
  .plot(kind="barh", ax=ax, color="steelblue")
ax.set_title("Top 30 features — XGBoost")
plt.tight_layout()
plt.savefig(OUTPUT_PATH+"feature_importance.png", dpi=150, bbox_inches="tight")
plt.show()

# SHAP
print("Calcul SHAP...")
explainer   = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)
plt.figure(figsize=(10,10))
shap.summary_plot(shap_values, X_test, feature_names=FEATURES_NUM+FEATURES_CAT, show=False)
plt.tight_layout()
plt.savefig(OUTPUT_PATH+"shap_summary.png", dpi=150, bbox_inches="tight")
plt.show()

# Physique
fig, ax = plt.subplots(figsize=(8,4))
ordre  = ["Faible","Modéré","Élevé","Critique"]
colors_bar = ["green","orange","red","darkred"]
df_physique["niveau_risque"].value_counts().reindex(ordre, fill_value=0) \
  .plot(kind="bar", ax=ax, color=colors_bar)
ax.set_title("Niveaux de risque — Segment Physique")
ax.set_xlabel("Niveau"); ax.set_ylabel("Nb entreprises")
plt.tight_layout()
plt.savefig(OUTPUT_PATH+"risque_physique.png", dpi=150, bbox_inches="tight")
plt.show()

# ── CELLULE 14 : Export ───────────────────────────────────────
print(f"\nExport vers {OUTPUT_PATH}...")

df_morale.to_parquet( OUTPUT_PATH+"morale_avec_predictions.parquet",  index=False)
df_morale.to_csv(     OUTPUT_PATH+"morale_avec_predictions.csv",      index=False)
df_physique.to_parquet(OUTPUT_PATH+"physique_avec_score.parquet",     index=False)
df_physique.to_csv(   OUTPUT_PATH+"physique_avec_score.csv",          index=False)

joblib.dump(xgb_model,  OUTPUT_PATH+"modele_xgboost.joblib")
joblib.dump(lgbm_model, OUTPUT_PATH+"modele_lightgbm.joblib")
joblib.dump(iso_forest, OUTPUT_PATH+"modele_isolation_forest.joblib")
joblib.dump(le_dict,    OUTPUT_PATH+"label_encoders.joblib")

features_info = {
    "validation"          : "temporelle",
    "cutoff"              : str(CUTOFF.date()),
    "leakage_supprime"    : FEATURES_LEAKAGE,
    "modele_1": {
        "nom"         : "XGBoost",
        "segment"     : "morale",
        "features_num": FEATURES_NUM,
        "features_cat": FEATURES_CAT,
        "cv_roc_auc"  : float(cv_results["XGBoost"]["test_roc_auc"].mean()),
        "cv_f1"       : float(cv_results["XGBoost"]["test_f1"].mean()),
        "cv_recall"   : float(cv_results["XGBoost"]["test_recall"].mean()),
        "test_auc"    : float(roc_auc_score(y_test, y_prob)),
    },
    "modele_2": {
        "nom"        : "Score_Règles",
        "segment"    : "physique",
        "score_moyen": float(df_physique["score_risque_physique"].mean()),
    },
    "modele_3": {
        "nom"         : "IsolationForest",
        "segment"     : "tous",
        "features"    : FEATURES_IF,
        "contamination": 0.05,
        "nb_anomalies": int(df_full["est_anomalie"].sum()),
    },
}
with open(OUTPUT_PATH+"features_info.json","w") as f:
    json.dump(features_info, f, indent=2, ensure_ascii=False)

print(f"""
{'='*60}
  TERMINE — 3 MODELES ENTRAINES
{'='*60}
  [Modele 1 - XGBoost/morale]
    Train    : cessées avant {CUTOFF.date()} + sans date
    Test     : cessées 2023 (jamais vues)
    CV AUC   : {cv_results['XGBoost']['test_roc_auc'].mean():.4f}
    Test AUC : {roc_auc_score(y_test, y_prob):.4f}

  [Modele 2 - Regles/physique]
    Score moyen : {df_physique['score_risque_physique'].mean():.1f}/100

  [Modele 3 - IsolationForest/tous]
    Anomalies  : {df_full['est_anomalie'].sum():,} entreprises

  Fichiers sauvegardes dans Drive/pfefmz/
{'='*60}
""")

# ============================================================
# PFEFM — ENTRAÎNEMENT COMPLET + COMPARAISON 4 MODÈLES
# Notebook Google Colab — Version finale corrigée
# ============================================================

# ── CELLULE 1 : Installation ──────────────────────────────────
!pip install xgboost lightgbm catboost shap --quiet

# ── CELLULE 2 : Imports ───────────────────────────────────────
import os, json, joblib, warnings, time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
warnings.filterwarnings("ignore")
from google.colab import drive

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score,
    roc_curve, average_precision_score, precision_recall_curve,
    ConfusionMatrixDisplay, f1_score, recall_score,
)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# ── CELLULE 3 : Google Drive + chargement ────────────────────
drive.mount('/content/drive')
OUTPUT_PATH = '/content/drive/MyDrive/pfefmz/'
os.makedirs(OUTPUT_PATH, exist_ok=True)
TODAY = pd.Timestamp("2026-03-30")

df = pd.read_parquet(OUTPUT_PATH + 'enterprises_clean.parquet')
print(f"Dataset : {df.shape[0]:,} lignes x {df.shape[1]} colonnes")

# ── CELLULE 4 : Séparation des segments ──────────────────────
df_morale   = df[df["typePersonneContent"].str.strip() == "morale"].copy().reset_index(drop=True)
df_physique = df[df["typePersonneContent"].str.strip() == "physique"].copy().reset_index(drop=True)

print(f"Morale   : {len(df_morale):,} | Cessées : {(df_morale['est_active']==0).sum():,}")
print(f"Physique : {len(df_physique):,} | Cessées : {(df_physique['est_active']==0).sum():,}")

# ── CELLULE 5 : Feature Engineering ─────────────────────────
def build_features(df_in):
    df = df_in.copy()

    codes_judiciaires = ["60","65","70","71","72","73","74","75"]
    df["dirigeant_role_str"] = df["dirigeant_role"].fillna("").astype(str).str.strip()
    df["dirigeant_est_judiciaire"]  = df["dirigeant_role_str"].isin(codes_judiciaires).astype(int)
    df["dirigeant_est_liquidateur"] = (df["dirigeant_role_str"] == "73").astype(int)
    df["dirigeant_est_mandataire"]  = (df["dirigeant_role_str"] == "65").astype(int)

    def parse_annee(ddn):
        try:
            s = str(ddn).strip()
            if len(s) >= 4 and s[:4].isdigit():
                return int(s[:4])
        except:
            pass
        return np.nan

    df["dirigeant_age"] = df["dirigeant_ddn"].apply(parse_annee)
    df["dirigeant_age"] = 2026 - df["dirigeant_age"]
    df["dirigeant_age"] = df["dirigeant_age"].where(df["dirigeant_age"].between(18, 100), np.nan)
    df["dirigeant_age_risque"] = np.where(
        df["dirigeant_age"].isna(), 0,
        ((df["dirigeant_age"] < 25) | (df["dirigeant_age"] > 70)).astype(int)
    )

    capital = pd.to_numeric(df["identite.montantCapital"], errors="coerce")
    df["capital_symbolique"]  = (capital == 1).astype(int)
    df["capital_tres_faible"] = capital.between(0, 1000, inclusive="both").astype(int)
    df["capital_absent"]      = capital.isna().astype(int)

    nb_rep = pd.to_numeric(df["nombreRepresentantsActifs"], errors="coerce").fillna(0)
    df["pas_representant_actif"] = (nb_rep == 0).astype(int)

    formes_obligatoires = ["5499","5710","5720","5599","5531","5560","5498","5308"]
    fj      = df["identite.formeJuridique"].fillna("").astype(str).str.strip()
    age_num = pd.to_numeric(df["age_ans"], errors="coerce").fillna(0)
    nb_ann  = pd.to_numeric(df.get("nb_annonces_bodacc",  pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    flag_depot = pd.to_numeric(df.get("flag_depot_comptes", pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    df["depot_non_respecte"] = (
        fj.isin(formes_obligatoires) & (flag_depot == 0) & (age_num > 2)
    ).astype(int)

    df["frequence_bodacc"] = np.where(age_num > 0, (nb_ann / age_num).round(4), 0.0)

    nb_etab_ouv = pd.to_numeric(df.get("nombreEtablissementsOuverts", pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    nb_obs      = pd.to_numeric(df.get("nb_observations",             pd.Series(0, index=df.index)), errors="coerce").fillna(0)
    taux        = pd.to_numeric(df.get("taux_cessation_sectoriel",    pd.Series(0, index=df.index)), errors="coerce").fillna(0)

    df["frequence_observations"] = np.where(age_num > 0, (nb_obs / age_num).round(4), 0.0)
    df["jeune_secteur_risque"]   = ((age_num < 3) & (taux > taux.mean())).astype(int)
    df["ancienne_inactive"]      = ((age_num > 20) & (nb_ann == 0) & (nb_etab_ouv == 0)).astype(int)

    est_micro = df.get("est_micro", pd.Series(0, index=df.index)).fillna(0).astype(int)
    df["micro_sans_capital"] = ((est_micro == 1) & (capital.isna() | (capital == 0))).astype(int)

    return df

df_morale   = build_features(df_morale)
df_physique = build_features(df_physique)
print("Features construites.")

# ── CELLULE 6 : Split temporel ───────────────────────────────
print("\n[Split temporel]")
df_morale["date_radiation"] = pd.to_datetime(
    df_morale["cessation.dateRadiation"], errors="coerce"
)

CUTOFF = pd.Timestamp("2023-01-01")

cessees_train     = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"] <  CUTOFF)]
cessees_test      = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"] >= CUTOFF)]
cessees_sans_date = df_morale[(df_morale["est_active"]==0) & (df_morale["date_radiation"].isna())]
actives           = df_morale[ df_morale["est_active"]==1]

ratio_split      = len(cessees_train) / max(len(cessees_train) + len(cessees_test), 1)
n_actives_train  = int(len(actives) * ratio_split)

actives_shuffled = actives.sample(frac=1, random_state=42)
actives_train    = actives_shuffled.iloc[:n_actives_train]
actives_test     = actives_shuffled.iloc[n_actives_train:]

df_train = pd.concat([cessees_train, cessees_sans_date, actives_train], ignore_index=True)
df_test  = pd.concat([cessees_test,  actives_test],                     ignore_index=True)

print(f"Train : {len(df_train):,} lignes | {(df_train['est_active']==0).sum()} cessées")
print(f"Test  : {len(df_test):,}  lignes | {(df_test['est_active']==0).sum()} cessées (2023 jamais vues)")

# ── CELLULE 7 : Features ML ──────────────────────────────────
FEATURES_LEAKAGE = [
    "pas_representant_actif",
    "capital_absent",
    "nombreRepresentantsActifs",
    "nombreEtablissementsOuverts",
    "jours_depuis_bodacc",
    "flag_cession_bodacc",
]

FEATURES_NUM = [
    "age_ans", "jours_depuis_update",
    "nb_etab_secondaires", "nb_etab_fermes", "nb_representants_extraits",
    "log_capital", "capital_symbolique", "capital_tres_faible",
    "nb_annonces_bodacc", "flag_procedure_collective",
    "flag_creation_bodacc", "flag_depot_comptes", "flag_modification_bodacc",
    "frequence_bodacc",
    "nb_observations", "nb_observations_critiques", "has_alerte_juridique",
    "frequence_observations",
    "dirigeant_est_judiciaire", "dirigeant_est_liquidateur", "dirigeant_est_mandataire",
    "dirigeant_age", "dirigeant_age_risque",
    "depot_non_respecte",
    "est_ess", "est_micro", "est_eirl", "est_agricole", "est_etranger",
    "multi_etablissement", "diffusion_insee", "micro_sans_capital",
    "taux_cessation_sectoriel", "age_median_sectoriel",
    "jeune_secteur_risque", "ancienne_inactive",
    "has_bilan", "bilan_chiffre_affaires", "bilan_resultat_net",
    "bilan_capitaux_propres", "bilan_total_actif",
    "bilan_marge_nette", "bilan_capitaux_negatifs",
]
FEATURES_CAT = [
    "forme_juridique_lib", "secteur_naf2", "stade_vie",
    "forme_juridique_risque", "departement",
]
FEATURES_NUM = [f for f in FEATURES_NUM if f in df_morale.columns]
FEATURES_CAT = [f for f in FEATURES_CAT if f in df_morale.columns]

print(f"Features ML : {len(FEATURES_NUM)+len(FEATURES_CAT)} | Leakage supprimé : {len(FEATURES_LEAKAGE)}")

# ── CELLULE 8 : Préparation des données ──────────────────────
def prepare_X(df_in, le_dict, fit=False):
    X = df_in[FEATURES_NUM + FEATURES_CAT].copy()
    for col in FEATURES_CAT:
        X[col] = X[col].fillna("Inconnu").astype(str)
        if fit:
            all_vals = list(X[col].unique()) + ["Inconnu"]
            le = LabelEncoder()
            le.fit(all_vals)
            X[col] = le.transform(X[col])
            le_dict[col] = le
        else:
            X[col] = le_dict[col].transform(
                X[col].map(lambda x: x if x in le_dict[col].classes_ else "Inconnu")
            )
    for col in FEATURES_NUM:
        X[col] = pd.to_numeric(X[col], errors="coerce")
    return X

le_dict = {}
X_train = prepare_X(df_train, le_dict, fit=True)
y_train = df_train["est_active"].astype(int)
X_test  = prepare_X(df_test,  le_dict, fit=False)
y_test  = df_test["est_active"].astype(int)

# Cast en float Python natif pour éviter l'erreur de clonage sklearn
ratio = float((y_train == 0).sum() / (y_train == 1).sum())
print(f"Ratio cessées/actives : {ratio:.3f}")

# ── CELLULE 9 : Définition des 4 modèles ─────────────────────
models = {
    "XGBoost": XGBClassifier(
        n_estimators=500, max_depth=6, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8,
        scale_pos_weight=ratio,
        eval_metric="logloss",
        random_state=42, n_jobs=-1,
    ),
    "LightGBM": LGBMClassifier(
        n_estimators=500, max_depth=6, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8,
        scale_pos_weight=ratio,
        random_state=42, n_jobs=-1, verbose=-1,
    ),
    "CatBoost": CatBoostClassifier(
        iterations=500, depth=6, learning_rate=0.05,
        auto_class_weights="Balanced",
        random_seed=42, verbose=0, thread_count=-1,
    ),
    "RandomForest": RandomForestClassifier(
        n_estimators=300, max_depth=12,
        min_samples_leaf=5, max_features="sqrt",
        class_weight="balanced",
        random_state=42, n_jobs=-1,
    ),
}

colors_map = {
    "XGBoost"     : "steelblue",
    "LightGBM"    : "darkorange",
    "CatBoost"    : "green",
    "RandomForest": "crimson",
}

# ── CELLULE 9b : Validation croisée ──────────────────────────
print("\n" + "=" * 65)
print("  COMPARAISON — XGBoost | LightGBM | CatBoost | RandomForest")
print("=" * 65)

cv      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring = ["roc_auc", "f1", "recall"]

print("\n[1/3] Validation croisée (5-fold StratifiedKFold)...\n")
cv_results  = {}
train_times = {}

for name, model in models.items():
    t0     = time.time()
    scores = cross_validate(model, X_train, y_train, cv=cv,
                            scoring=scoring, n_jobs=-1)
    elapsed           = round(time.time() - t0, 1)
    cv_results[name]  = scores
    train_times[name] = elapsed
    print(f"  {name:<14} "
          f"ROC-AUC {scores['test_roc_auc'].mean():.4f}±{scores['test_roc_auc'].std():.4f} | "
          f"F1 {scores['test_f1'].mean():.4f} | "
          f"Recall {scores['test_recall'].mean():.4f} | "
          f"{elapsed}s")

# ── CELLULE 9c : Entraînement final ──────────────────────────
print("\n[2/3] Entraînement final sur X_train complet...\n")
fitted = {}
for name, model in models.items():
    t0 = time.time()
    model.fit(X_train, y_train)
    fitted[name] = model
    print(f"  {name:<14} entraîné en {round(time.time()-t0, 1)}s")

# ── CELLULE 9d : Évaluation détaillée par modèle ─────────────
print("\n[3/3] Évaluation détaillée sur le test temporel (2023+)...\n")

test_results = {}
probas       = {}
preds        = {}

for name, model in fitted.items():
    p    = model.predict_proba(X_test)[:, 1]
    pred = model.predict(X_test)
    probas[name] = p
    preds[name]  = pred
    test_results[name] = {
        "ROC-AUC": round(roc_auc_score(y_test, p),  4),
        "F1"     : round(f1_score(y_test, pred),     4),
        "Recall" : round(recall_score(y_test, pred), 4),
    }

    # ── Rapport détaillé identique au screenshot ──────────────
    print("─" * 55)
    print(f"  {name} Test ROC-AUC : {test_results[name]['ROC-AUC']}")
    print(classification_report(
        y_test, pred,
        target_names=["Cessée", "Active"],
        digits=2,
    ))

    # Cessées 2023 détectées
    mask_cess = y_test == 0
    n_det = (pred[mask_cess] == 0).sum()
    n_tot = mask_cess.sum()
    print(f"  Cessées 2023 détectées : {n_det}/{n_tot} ({n_det/n_tot*100:.1f}%)\n")

# Aliases compatibilité cellules suivantes
xgb_model  = fitted["XGBoost"]
lgbm_model = fitted["LightGBM"]
y_prob     = probas["XGBoost"]
y_pred     = preds["XGBoost"]

# ── CELLULE 9e : Tableau comparatif ──────────────────────────
print("=" * 65)
print("  TABLEAU RÉCAPITULATIF")
print("=" * 65)

rows = []
for name in models:
    cv_s = cv_results[name]
    ts   = test_results[name]
    rows.append({
        "Modèle"        : name,
        "CV AUC (mean)" : f"{cv_s['test_roc_auc'].mean():.4f}",
        "CV AUC (std)"  : f"{cv_s['test_roc_auc'].std():.4f}",
        "CV F1"         : f"{cv_s['test_f1'].mean():.4f}",
        "CV Recall"     : f"{cv_s['test_recall'].mean():.4f}",
        "Test ROC-AUC"  : ts["ROC-AUC"],
        "Test F1"       : ts["F1"],
        "Test Recall"   : ts["Recall"],
        "Temps CV (s)"  : train_times[name],
    })

df_compare = pd.DataFrame(rows).set_index("Modèle")
print(df_compare.to_string())

winner_auc    = df_compare["Test ROC-AUC"].astype(float).idxmax()
winner_recall = df_compare["Test Recall"].astype(float).idxmax()
winner_f1     = df_compare["Test F1"].astype(float).idxmax()

print(f"\n  ★ Meilleur ROC-AUC  → {winner_auc}")
print(f"  ★ Meilleur Recall   → {winner_recall}  ← prioritaire cessations")
print(f"  ★ Meilleur F1       → {winner_f1}")

df_compare.to_csv(OUTPUT_PATH + "comparaison_modeles.csv")

# ── CELLULE 9f : Courbes ROC & Precision-Recall comparées ────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].plot([0, 1], [0, 1], "--", color="gray", lw=1)
for name, p in probas.items():
    fpr, tpr, _ = roc_curve(y_test, p)
    axes[0].plot(fpr, tpr,
                 label=f"{name} (AUC={test_results[name]['ROC-AUC']})",
                 color=colors_map[name], lw=2)
axes[0].set(title="Courbes ROC — Test temporel 2023",
            xlabel="Taux Faux Positifs", ylabel="Taux Vrais Positifs")
axes[0].legend(loc="lower right")
axes[0].grid(alpha=0.3)

for name, p in probas.items():
    prec, rec, _ = precision_recall_curve(y_test, p)
    ap_val       = average_precision_score(y_test, p)
    axes[1].plot(rec, prec,
                 label=f"{name} (AP={ap_val:.4f})",
                 color=colors_map[name], lw=2)
axes[1].set(title="Courbes Precision-Recall — Test temporel 2023",
            xlabel="Recall", ylabel="Precision")
axes[1].legend(loc="upper right")
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig(OUTPUT_PATH + "comparaison_roc_pr.png", dpi=150, bbox_inches="tight")
plt.show()

# ── CELLULE 9g : Feature importance — 4 modèles ──────────────
FEATURE_NAMES = FEATURES_NUM + FEATURES_CAT

def get_importances(name, model):
    if name in ("XGBoost", "LightGBM", "RandomForest"):
        imp = model.feature_importances_
    elif name == "CatBoost":
        imp = model.get_feature_importance()
    else:
        return None
    s = pd.Series(imp, index=FEATURE_NAMES)
    return (s / s.sum()).round(5)

fig, axes = plt.subplots(2, 2, figsize=(18, 20))
axes = axes.flatten()

for idx, (name, model) in enumerate(fitted.items()):
    imp_series = get_importances(name, model)
    if imp_series is None:
        continue
    imp_series.sort_values(ascending=True).tail(20).plot(
        kind="barh", ax=axes[idx], color=colors_map[name]
    )
    axes[idx].set_title(f"Top 20 features — {name}", fontsize=13)
    axes[idx].set_xlabel("Importance normalisée")
    axes[idx].grid(axis="x", alpha=0.3)

plt.suptitle("Importance des features par modèle", fontsize=15, y=1.01)
plt.tight_layout()
plt.savefig(OUTPUT_PATH + "feature_importance_comparaison.png", dpi=150, bbox_inches="tight")
plt.show()

print("\n── Top 10 features — consensus inter-modèles ──")
consensus = pd.DataFrame({
    name: get_importances(name, model)
    for name, model in fitted.items()
})
consensus["moyenne"] = consensus.mean(axis=1)
print(consensus["moyenne"].sort_values(ascending=False).head(10).round(4).to_string())

# ── CELLULE 9h : Analyse finale ───────────────────────────────
print(f"""
{'=' * 65}
  ANALYSE COMPARATIVE FINALE
{'=' * 65}
┌─────────────────────────────────────────────────────────────┐
│  Meilleur ROC-AUC  → {winner_auc:<14}
│  Meilleur Recall   → {winner_recall:<14}  ★ prioritaire cessations
│  Meilleur F1       → {winner_f1:<14}
└─────────────────────────────────────────────────────────────┘

Notes d'interprétation :
  • XGBoost / LightGBM   : boosting séquentiel, très efficace sur
                            données tabulaires déséquilibrées.
  • CatBoost             : auto_class_weights gère le déséquilibre,
                            robuste aux données bruyantes.
  • RandomForest         : faible variance, Recall souvent plus bas
                            (pas de boosting séquentiel).

  → Pour détecter les cessations : priorisez le Recall.
  → Écart AUC < 0.02 entre modèles → robustesse temporelle confirmée.
""")

# ── CELLULE 10 : Score physique ───────────────────────────────
print("\n" + "=" * 60)
print("  MODELE — SCORE REGLES METIER — PHYSIQUE")
print("=" * 60)

def score_physique(row):
    score = 60.0
    score -= row.get("flag_procedure_collective",    0) * 40
    score -= row.get("has_alerte_juridique",          0) * 30
    score -= row.get("dirigeant_est_judiciaire",      0) * 25
    score -= row.get("dirigeant_est_liquidateur",     0) * 15
    score -= row.get("depot_non_respecte",            0) * 10
    score -= row.get("pas_representant_actif",        0) * 10
    score -= min(row.get("nb_annonces_bodacc",        0) * 2, 10)
    score -= min(row.get("nb_observations_critiques", 0) * 5, 20)
    score -= row.get("capital_absent",                0) * 5
    score -= row.get("capital_tres_faible",           0) * 3
    taux = row.get("taux_cessation_sectoriel", 0.068) or 0.068
    score -= min(max(0, (taux / 0.068 - 1) * 5), 10)
    return round(max(0, min(100, score)), 2)

def niveau_risque(score):
    if score >= 65: return "Faible"
    if score >= 45: return "Modéré"
    if score >= 25: return "Élevé"
    return "Critique"

df_physique["score_risque_physique"] = df_physique.apply(score_physique, axis=1)
df_physique["niveau_risque"]         = df_physique["score_risque_physique"].apply(niveau_risque)

print(f"\nDistribution :")
print(df_physique["niveau_risque"].value_counts())
print(f"Score moyen : {df_physique['score_risque_physique'].mean():.1f}")

# ── CELLULE 11 : Isolation Forest ────────────────────────────
print("\n" + "=" * 60)
print("  ISOLATION FOREST — TOUS")
print("=" * 60)

FEATURES_IF = [f for f in [
    "age_ans", "log_capital",
    "nb_annonces_bodacc", "flag_procedure_collective",
    "has_alerte_juridique", "nb_observations_critiques",
    "dirigeant_est_judiciaire", "frequence_bodacc",
    "taux_cessation_sectoriel", "depot_non_respecte",
] if f in df_morale.columns]

X_actives = df_morale[df_morale["est_active"]==1][FEATURES_IF].copy()
for col in FEATURES_IF:
    X_actives[col] = pd.to_numeric(X_actives[col], errors="coerce").fillna(0)

iso_forest = IsolationForest(n_estimators=200, contamination=0.05,
                              random_state=42, n_jobs=-1)
iso_forest.fit(X_actives)
print(f"Entraîné sur {len(X_actives):,} actives")

df_full   = pd.concat([df_morale, df_physique], ignore_index=True)
X_if_full = df_full[FEATURES_IF].copy()
for col in FEATURES_IF:
    X_if_full[col] = pd.to_numeric(X_if_full[col], errors="coerce").fillna(0)

df_full["anomalie_score"] = iso_forest.decision_function(X_if_full).round(4)
df_full["est_anomalie"]   = (iso_forest.predict(X_if_full) == -1).astype(int)
print(f"Anomalies détectées : {df_full['est_anomalie'].sum():,} / {len(df_full):,}")

# ── CELLULE 12 : Prédictions finales (meilleur Recall) ───────
print("\nPrédictions finales...")

best_model_recall = fitted[winner_recall]
X_full_morale     = prepare_X(df_morale, le_dict, fit=False)

df_morale["proba_cessee"]    = best_model_recall.predict_proba(X_full_morale)[:, 0].round(4)
df_morale["proba_active"]    = best_model_recall.predict_proba(X_full_morale)[:, 1].round(4)
df_morale["prediction_ml"]   = best_model_recall.predict(X_full_morale)
df_morale["score_confiance"] = df_morale[["proba_active","proba_cessee"]].max(axis=1).round(4)
df_morale["modele_utilise"]  = winner_recall

def cat_morale(p):
    if p >= 0.75: return "Risque très élevé"
    if p >= 0.50: return "Risque élevé"
    if p >= 0.30: return "Risque modéré"
    return "Faible risque"

df_morale["categorie_prediction"] = df_morale["proba_cessee"].apply(cat_morale)

df_physique["proba_cessee"]         = np.nan
df_physique["proba_active"]         = np.nan
df_physique["prediction_ml"]        = np.nan
df_physique["score_confiance"]      = np.nan
df_physique["modele_utilise"]       = "Score_Règles"
df_physique["categorie_prediction"] = df_physique["niveau_risque"].map({
    "Critique": "Risque très élevé",
    "Élevé":    "Risque élevé",
    "Modéré":   "Risque modéré",
    "Faible":   "Faible risque",
})

cess_det = (df_morale[df_morale["est_active"]==0]["prediction_ml"] == 0).sum()
cess_tot = (df_morale["est_active"] == 0).sum()
print(f"[Morale]   Cessées détectées : {cess_det}/{cess_tot} ({cess_det/cess_tot*100:.1f}%)")
print(f"[Physique] Risque élevé+critique : {(df_physique['niveau_risque'].isin(['Élevé','Critique'])).sum()}")

# ── CELLULE 13 : Graphiques ───────────────────────────────────
y_prob_best = probas[winner_recall]
y_pred_best = preds[winner_recall]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

cm_val = confusion_matrix(y_test, y_pred_best)
ConfusionMatrixDisplay(cm_val, display_labels=["Cessée","Active"]).plot(
    ax=axes[0], colorbar=False)
axes[0].set_title(f"Matrice confusion — {winner_recall} — Test 2023")

fpr, tpr, _ = roc_curve(y_test, y_prob_best)
axes[1].plot(fpr, tpr,
             label=f"AUC={roc_auc_score(y_test, y_prob_best):.4f}",
             color=colors_map.get(winner_recall, "steelblue"), lw=2)
axes[1].plot([0, 1], [0, 1], "--", color="gray")
axes[1].set(title=f"Courbe ROC — {winner_recall}",
            xlabel="Faux positifs", ylabel="Vrais positifs")
axes[1].legend()

prec, rec, _ = precision_recall_curve(y_test, y_prob_best)
axes[2].plot(rec, prec,
             label=f"AP={average_precision_score(y_test, y_prob_best):.4f}",
             color="coral", lw=2)
axes[2].set(title="Precision-Recall", xlabel="Recall", ylabel="Precision")
axes[2].legend()

plt.tight_layout()
plt.savefig(OUTPUT_PATH + "evaluation_temporelle.png", dpi=150, bbox_inches="tight")
plt.show()

# Feature importance meilleur modèle
fig, ax = plt.subplots(figsize=(10, 10))
imp_best = get_importances(winner_recall, fitted[winner_recall])
imp_best.sort_values(ascending=True).tail(30).plot(
    kind="barh", ax=ax, color=colors_map.get(winner_recall, "steelblue"))
ax.set_title(f"Top 30 features — {winner_recall} (meilleur Recall)")
plt.tight_layout()
plt.savefig(OUTPUT_PATH + "feature_importance.png", dpi=150, bbox_inches="tight")
plt.show()

# SHAP
print(f"Calcul SHAP sur {winner_recall}...")
explainer   = shap.TreeExplainer(fitted[winner_recall])
shap_values = explainer.shap_values(X_test)
sv = shap_values[1] if isinstance(shap_values, list) else shap_values
plt.figure(figsize=(10, 10))
shap.summary_plot(sv, X_test, feature_names=FEATURE_NAMES, show=False)
plt.tight_layout()
plt.savefig(OUTPUT_PATH + "shap_summary.png", dpi=150, bbox_inches="tight")
plt.show()

# Physique
fig, ax = plt.subplots(figsize=(8, 4))
ordre      = ["Faible","Modéré","Élevé","Critique"]
colors_bar = ["green","orange","red","darkred"]
df_physique["niveau_risque"].value_counts().reindex(ordre, fill_value=0) \
    .plot(kind="bar", ax=ax, color=colors_bar)
ax.set_title("Niveaux de risque — Segment Physique")
ax.set_xlabel("Niveau")
ax.set_ylabel("Nb entreprises")
plt.tight_layout()
plt.savefig(OUTPUT_PATH + "risque_physique.png", dpi=150, bbox_inches="tight")
plt.show()

# ── CELLULE 14 : Export ───────────────────────────────────────
print(f"\nExport vers {OUTPUT_PATH}...")

df_morale.to_parquet( OUTPUT_PATH + "morale_avec_predictions.parquet",  index=False)
df_morale.to_csv(     OUTPUT_PATH + "morale_avec_predictions.csv",      index=False)
df_physique.to_parquet(OUTPUT_PATH + "physique_avec_score.parquet",     index=False)
df_physique.to_csv(   OUTPUT_PATH + "physique_avec_score.csv",          index=False)

joblib.dump(fitted["XGBoost"],      OUTPUT_PATH + "modele_xgboost.joblib")
joblib.dump(fitted["LightGBM"],     OUTPUT_PATH + "modele_lightgbm.joblib")
joblib.dump(fitted["CatBoost"],     OUTPUT_PATH + "modele_catboost.joblib")
joblib.dump(fitted["RandomForest"], OUTPUT_PATH + "modele_random_forest.joblib")
joblib.dump(iso_forest,             OUTPUT_PATH + "modele_isolation_forest.joblib")
joblib.dump(le_dict,                OUTPUT_PATH + "label_encoders.joblib")

features_info = {
    "validation"      : "temporelle",
    "cutoff"          : str(CUTOFF.date()),
    "leakage_supprime": FEATURES_LEAKAGE,
    "meilleur_auc"    : winner_auc,
    "meilleur_recall" : winner_recall,
    "modeles"         : {},
    "modele_physique" : {
        "nom"        : "Score_Règles",
        "segment"    : "physique",
        "score_moyen": float(df_physique["score_risque_physique"].mean()),
    },
    "modele_anomalie" : {
        "nom"          : "IsolationForest",
        "segment"      : "tous",
        "contamination": 0.05,
        "nb_anomalies" : int(df_full["est_anomalie"].sum()),
    },
}
for name in models:
    cv_s = cv_results[name]
    ts   = test_results[name]
    features_info["modeles"][name] = {
        "cv_roc_auc_mean": float(cv_s["test_roc_auc"].mean()),
        "cv_roc_auc_std" : float(cv_s["test_roc_auc"].std()),
        "cv_f1_mean"     : float(cv_s["test_f1"].mean()),
        "cv_recall_mean" : float(cv_s["test_recall"].mean()),
        "test_roc_auc"   : ts["ROC-AUC"],
        "test_f1"        : ts["F1"],
        "test_recall"    : ts["Recall"],
        "temps_cv_s"     : train_times[name],
    }

with open(OUTPUT_PATH + "features_info.json", "w") as f:
    json.dump(features_info, f, indent=2, ensure_ascii=False)

print(f"""
{'='*65}
  TERMINÉ — 4 MODÈLES COMPARÉS + PIPELINE COMPLET
{'='*65}
""")
print(df_compare.to_string())
print(f"""
  ★ Meilleur ROC-AUC  : {winner_auc}
  ★ Meilleur Recall   : {winner_recall}
  ★ Meilleur F1       : {winner_f1}

  [Score Règles / Physique]
    Score moyen : {df_physique['score_risque_physique'].mean():.1f}/100

  [Isolation Forest / Tous]
    Anomalies   : {df_full['est_anomalie'].sum():,} entreprises

  Fichiers sauvegardés dans Drive/pfefmz/
{'='*65}
""")



# ============================================================
# CORRECTION XGBOOST 2026
# ton xgboost version = callbacks NON supporté dans fit()
# donc early stopping doit être mis dans le constructeur



# !!!!!!!!!!!!!!!! remarque !!!!!!!!!! on na pas de overfeating car
 # Gap=AUC train -auc test

# Un gap inférieur à 0.01 est généralement excellent. ============================================================

# INSTALLATION
!pip install -U xgboost lightgbm catboost --quiet


# ============================================================
# IMPORTS
# ============================================================
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score, recall_score
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier, early_stopping
from catboost import CatBoostClassifier


# ============================================================
# DATA
# ============================================================
df = pd.read_parquet('/content/drive/MyDrive/pfefmz/enterprises_clean.parquet')

y = df["est_active"]

X = df.select_dtypes(include=np.number).drop(columns=["est_active"], errors="ignore")
X = X.fillna(0)


# ============================================================
# SPLIT
# ============================================================
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.20,
    stratify=y_temp,
    random_state=42
)


# ============================================================
# MODELES
# ============================================================
models = {

    "XGBoost": XGBClassifier(
        n_estimators=1000,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        early_stopping_rounds=30,
        random_state=42
    ),

    "LightGBM": LGBMClassifier(
        n_estimators=1000,
        max_depth=6,
        learning_rate=0.05,
        random_state=42
    ),

    "CatBoost": CatBoostClassifier(
        iterations=1000,
        depth=6,
        learning_rate=0.05,
        early_stopping_rounds=30,
        verbose=0,
        random_seed=42
    ),

    "RandomForest": RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
}


# ============================================================
# TRAIN
# ============================================================
fitted = {}

for name, model in models.items():

    print("="*60)
    print(name)

    if name == "XGBoost":

        model.fit(
            X_train,
            y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )

    elif name == "LightGBM":

        model.fit(
            X_train,
            y_train,
            eval_set=[(X_val, y_val)],
            eval_metric="auc",
            callbacks=[early_stopping(30, verbose=False)]
        )

    elif name == "CatBoost":

        model.fit(
            X_train,
            y_train,
            eval_set=(X_val, y_val),
            verbose=False
        )

    else:

        model.fit(X_train, y_train)

    fitted[name] = model


# ============================================================
# RESULTATS
# ============================================================
rows = []

for name, model in fitted.items():

    p_train = model.predict_proba(X_train)[:,1]
    p_test = model.predict_proba(X_test)[:,1]
    pred = model.predict(X_test)

    auc_train = roc_auc_score(y_train, p_train)
    auc_test = roc_auc_score(y_test, p_test)

    f1 = f1_score(y_test, pred)
    rec = recall_score(y_test, pred)

    gap = auc_train - auc_test

    rows.append([
        name,
        round(auc_train,4),
        round(auc_test,4),
        round(gap,4),
        round(f1,4),
        round(rec,4)
    ])


df_resultats = pd.DataFrame(rows, columns=[
    "Modele",
    "AUC_Train",
    "AUC_Test",
    "Gap",
    "F1",
    "Recall"
])

print(df_resultats)

!pip install transformers torch sentence-transformers -q
print("Installation terminée")

from google.colab import drive
drive.mount('/content/drive')