# -*- coding: utf-8 -*-
"""PFEFM_ML_Leakage_Audit_CatBoost_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rPq5nIGZQE-wlCBvfVIAnHDnOQY-5sd

# PFEFM — Leakage Audit & CatBoost Comparison

Standalone Colab notebook. **Does not import from your `ml_model/` package** — it re-implements the corrected pipeline end-to-end so you can audit results independently.

**Target:** `1 = cessée`, `0 = active`.  
**Segment:** moral entities only (`typePersonneContent == 'morale'`).  
**Pipeline:** temporal split → leakage audit (drops 5 features known/suspected to leak) → train XGBoost / LightGBM / CatBoost on the same splits → calibrate → threshold tune → SHAP → export to Drive.

The leakage audit trains every model **twice** (with and without leaky features) so you see the honest PR-AUC delta, not just the inflated number.

**Reads:** `/content/drive/MyDrive/pfefmz/enterprises_clean.parquet`  
**Writes:** `/content/drive/MyDrive/pfefmz/colab_audit/` (created on first run)

## 1. Install dependencies
"""

!pip install -q xgboost lightgbm catboost shap scikit-learn pandas pyarrow matplotlib seaborn

"""## 2. Imports & Google Drive"""

import os, json, warnings, pickle
from datetime import date, datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.cluster import KMeans
from sklearn.inspection import permutation_importance
from sklearn.metrics import (
    roc_auc_score, average_precision_score, brier_score_loss,
    precision_recall_curve, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report,
)

import xgboost as xgb
import lightgbm as lgb
import catboost as cb
import shap

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
pd.set_option('display.max_columns', 100)

from google.colab import drive
drive.mount('/content/drive')

"""## 3. Configuration

Edit values in this cell only. Everything else is data-driven.
"""

INPUT_PATH = '/content/drive/MyDrive/pfefmz/enterprises_clean.parquet'
OUTPUT_DIR = '/content/drive/MyDrive/pfefmz/colab_audit/'
os.makedirs(OUTPUT_DIR, exist_ok=True)

REFERENCE_DATE = date(2026, 1, 1)
TEST_CUTOFF    = date(2023, 1, 1)   # rows with observation_date >= this go to test

RANDOM_STATE = 42

# Threshold-tuning constraint: minimum recall on the cessation class.
MIN_RECALL = 0.95

# Cost-sensitive threshold: how much more painful is missing a failure vs a false alarm?
COST_FN = 20.0
COST_FP = 1.0

# Features the registry / our analysis flagged as leaky. Removed from the supervised model.
LEAKY_FEATURES = [
    'dirigeant_est_liquidateur',     # role 73 = liquidator, appointed AS PART OF cessation
    'dirigeant_est_mandataire',      # role 65 = administrator, appointed in collective procedures
    'dirigeant_est_judiciaire',      # umbrella judicial-role flag
    'flag_procedure_collective',     # sauvegarde / redressement / liquidation = the event itself
    'jours_depuis_update',           # used to derive observation_date for actives → encodes the split
]

RUN_TAG = datetime.now().strftime('%Y%m%d_%H%M%S')
print(f'Run tag: {RUN_TAG}')
print(f'Output : {OUTPUT_DIR}')

"""## 4. Load data & filter to moral entities"""

df_raw = pd.read_parquet(INPUT_PATH)
print(f'Loaded {len(df_raw):,} rows × {df_raw.shape[1]} columns')

if 'typePersonneContent' in df_raw.columns:
    seg = df_raw['typePersonneContent'].fillna('').astype(str).str.strip().str.lower()
    df = df_raw.loc[seg == 'morale'].copy().reset_index(drop=True)
    print(f'Morale subset: {len(df):,} rows')
else:
    df = df_raw.copy()
    print('typePersonneContent missing — using full dataset')

# Target: 1 = cessée, 0 = active.
if 'est_active' not in df.columns:
    raise KeyError('Column `est_active` is required to build the target.')
df['target'] = (df['est_active'] == 0).astype(int)

n_pos = int(df['target'].sum())
n_neg = int((1 - df['target']).sum())
print(f'Cessées (1): {n_pos:,} | Actives (0): {n_neg:,} | Imbalance: {n_pos / len(df):.1%}')

"""## 5. Feature engineering

Self-contained copy of `build_features` from the project so the notebook does not depend on the package. Logic is identical to `ml_model/pfefm_train/feature_engineering.py`.
"""

# ============================================================
# 5. Feature engineering — version améliorée
# Objectifs :
# - mieux détecter les faux négatifs silencieux
# - réduire la dépendance aux signaux juridiques
# - renforcer les signaux financiers
# ============================================================

JUDICIAL_ROLE_CODES = ("60", "65", "70", "71", "72", "73", "74", "75")
MANDATORY_DEPOT_FORMS = ("5499", "5710", "5720", "5599", "5531", "5560", "5498", "5308")

def _num(df, col, default=0.0):
    if col not in df.columns:
        return pd.Series(default, index=df.index, dtype="float64")
    return pd.to_numeric(df[col], errors="coerce").fillna(default)

def _num_nullable(df, col):
    if col not in df.columns:
        return pd.Series(np.nan, index=df.index, dtype="float64")
    return pd.to_numeric(df[col], errors="coerce")

def _safe_div(a, b):
    return np.where(np.abs(b) > 1e-9, a / b, 0.0)

def _parse_year(s):
    def one(v):
        if v is None:
            return np.nan
        t = str(v).strip()
        return int(t[:4]) if len(t) >= 4 and t[:4].isdigit() else np.nan
    return s.map(one).astype("float64")

def build_features(df, reference_year=2026):
    out = df.copy()

    role_str = out.get("dirigeant_role", pd.Series("", index=out.index)).fillna("").astype(str).str.strip()

    out["dirigeant_role_str"] = role_str
    out["dirigeant_est_judiciaire"] = role_str.isin(JUDICIAL_ROLE_CODES).astype(int)
    out["dirigeant_est_liquidateur"] = (role_str == "73").astype(int)
    out["dirigeant_est_mandataire"] = (role_str == "65").astype(int)

    if "dirigeant_ddn" in out.columns:
        year = _parse_year(out["dirigeant_ddn"])
        age = reference_year - year
        age = age.where(age.between(18, 100), np.nan)
        out["dirigeant_age"] = age
        out["dirigeant_age_risque"] = np.where(
            age.isna(),
            0,
            ((age < 25) | (age > 70)).astype(int)
        )
    else:
        out["dirigeant_age"] = np.nan
        out["dirigeant_age_risque"] = 0

    capital = _num_nullable(out, "identite.montantCapital")

    out["capital_symbolique"] = (capital == 1).astype(int)
    out["capital_tres_faible"] = capital.between(0, 1000, inclusive="both").astype(int)
    out["capital_absent"] = capital.isna().astype(int)
    out["log_capital_safe"] = np.log1p(capital.fillna(0).clip(lower=0))

    nb_rep_actifs = _num(out, "nombreRepresentantsActifs", 0)
    nb_rep_extraits = _num(out, "nb_representants_extraits", 0)

    out["pas_representant_actif"] = (nb_rep_actifs == 0).astype(int)
    out["representants_peu_nombreux"] = (nb_rep_extraits <= 1).astype(int)

    nb_etab_fermes = _num(out, "nb_etab_fermes", 0)
    nb_etab_secondaires = _num(out, "nb_etab_secondaires", 0)

    out["ratio_etab_fermes"] = _safe_div(
        nb_etab_fermes,
        nb_etab_fermes + nb_etab_secondaires + 1
    )

    out["a_ferme_etablissement"] = (nb_etab_fermes > 0).astype(int)

    fj = out.get("identite.formeJuridique", pd.Series("", index=out.index)).fillna("").astype(str).str.strip()

    age_num = _num(out, "age_ans", 0.0)
    nb_ann = _num(out, "nb_annonces_bodacc", 0.0)
    flag_depot = _num(out, "flag_depot_comptes", 0.0)

    out["depot_non_respecte"] = (
        fj.isin(MANDATORY_DEPOT_FORMS) &
        (flag_depot == 0) &
        (age_num > 2)
    ).astype(int)

    nb_obs = _num(out, "nb_observations", 0.0)
    nb_obs_crit = _num(out, "nb_observations_critiques", 0.0)

    out["frequence_bodacc"] = np.where(age_num > 0, (nb_ann / age_num).round(4), 0.0)
    out["frequence_observations"] = np.where(age_num > 0, (nb_obs / age_num).round(4), 0.0)
    out["frequence_observations_critiques"] = np.where(age_num > 0, (nb_obs_crit / age_num).round(4), 0.0)

    out["ratio_observations_critiques"] = _safe_div(nb_obs_crit, nb_obs + 1)

    has_alerte = _num(out, "has_alerte_juridique", 0)
    flag_proc = _num(out, "flag_procedure_collective", 0)

    out["profil_silencieux"] = (
        (has_alerte == 0) &
        (flag_proc == 0) &
        (nb_obs_crit <= 1) &
        (nb_ann <= 3)
    ).astype(int)

    out["silencieux_mais_fragile"] = (
        (out["profil_silencieux"] == 1) &
        (
            (out["capital_tres_faible"] == 1) |
            (out["depot_non_respecte"] == 1) |
            (out["representants_peu_nombreux"] == 1)
        )
    ).astype(int)

    out["jeune_silencieuse_fragile"] = (
        (age_num < 3) &
        (out["silencieux_mais_fragile"] == 1)
    ).astype(int)

    out["ancienne_silencieuse_fragile"] = (
        (age_num > 10) &
        (out["silencieux_mais_fragile"] == 1)
    ).astype(int)

    taux = _num(out, "taux_cessation_sectoriel", 0.0)
    taux_mean = float(taux.mean()) if len(taux) else 0.0

    out["jeune_secteur_risque"] = ((age_num < 3) & (taux > taux_mean)).astype(int)
    out["secteur_risque_eleve"] = (taux > taux.quantile(0.75)).astype(int)

    out["risque_sectoriel_x_fragilite"] = (
        out["secteur_risque_eleve"] *
        (
            out["capital_tres_faible"] |
            out["depot_non_respecte"] |
            out["representants_peu_nombreux"]
        ).astype(int)
    )

    nb_etab_ouv = _num(out, "nombreEtablissementsOuverts", 0.0)

    out["ancienne_inactive"] = (
        (age_num > 20) &
        (nb_ann == 0) &
        (nb_etab_ouv == 0)
    ).astype(int)

    est_micro = _num(out, "est_micro", 0).astype(int)

    out["micro_sans_capital"] = (
        (est_micro == 1) &
        (capital.isna() | (capital == 0))
    ).astype(int)

    ca = _num_nullable(out, "bilan_chiffre_affaires")
    resultat = _num_nullable(out, "bilan_resultat_net")
    capitaux = _num_nullable(out, "bilan_capitaux_propres")
    total_actif = _num_nullable(out, "bilan_total_actif")
    marge = _num_nullable(out, "bilan_marge_nette")

    out["bilan_capitaux_negatifs"] = (capitaux < 0).fillna(False).astype(int)

    out["bilan_resultat_negatif"] = (resultat < 0).fillna(False).astype(int)
    out["bilan_ca_absent"] = ca.isna().astype(int)
    out["bilan_resultat_absent"] = resultat.isna().astype(int)
    out["bilan_capitaux_absents"] = capitaux.isna().astype(int)

    out["rentabilite_resultat_sur_ca"] = _safe_div(
        resultat.fillna(0),
        ca.fillna(0) + 1
    )

    out["solidite_capitaux_sur_actif"] = _safe_div(
        capitaux.fillna(0),
        total_actif.fillna(0) + 1
    )

    out["capital_sur_actif"] = _safe_div(
        capital.fillna(0),
        total_actif.fillna(0) + 1
    )

    out["marge_nette_faible"] = (marge.fillna(0) < 0.02).astype(int)
    out["marge_nette_negative"] = (marge.fillna(0) < 0).astype(int)

    out["fragilite_financiere"] = (
        (out["capital_tres_faible"] == 1) |
        (out["bilan_capitaux_negatifs"] == 1) |
        (out["bilan_resultat_negatif"] == 1) |
        (out["marge_nette_negative"] == 1)
    ).astype(int)

    out["fragilite_financiere_sans_alerte"] = (
        (out["fragilite_financiere"] == 1) &
        (has_alerte == 0) &
        (flag_proc == 0)
    ).astype(int)

    out["juridique_x_financier"] = (
        ((has_alerte == 1) | (nb_obs_crit > 1)).astype(int) *
        out["fragilite_financiere"]
    )

    out["bodacc_x_financier"] = (
        (out["frequence_bodacc"] > out["frequence_bodacc"].quantile(0.75)).astype(int) *
        out["fragilite_financiere"]
    )

    out["secteur_x_financier"] = (
        out["secteur_risque_eleve"] *
        out["fragilite_financiere"]
    )

    return out


df_fe = build_features(df, reference_year=REFERENCE_DATE.year)

print(f"After feature engineering: {df_fe.shape[1]} columns")

# ============================================================
# 5bis — Features anti faux négatifs silencieux renforcées
# À exécuter juste après :
# df_fe = build_features(df, reference_year=REFERENCE_DATE.year)
# ============================================================

def add_silent_failure_features(df):
    df = df.copy()

    required_cols = [
        "nb_observations",
        "nb_observations_critiques",
        "has_alerte_juridique",
        "nb_annonces_bodacc",
        "fragilite_financiere",
        "capital_tres_faible",
        "depot_non_respecte",
        "profil_silencieux",
        "silencieux_mais_fragile",
        "bilan_resultat_net",
        "bilan_capitaux_propres",
    ]

    for col in required_cols:
        if col not in df.columns:
            df[col] = 0

    df["absence_signal_juridique"] = (
        (df["nb_observations"] == 0) &
        (df["nb_observations_critiques"] == 0) &
        (df["has_alerte_juridique"] == 0)
    ).astype(int)

    df["faible_activite_legale"] = (
        (df["nb_annonces_bodacc"] <= 1) &
        (df["nb_observations"] <= 1)
    ).astype(int)

    df["faible_visibilite"] = (
        (df["absence_signal_juridique"] == 1) &
        (df["faible_activite_legale"] == 1)
    ).astype(int)

    df["silencieuse_fragile_v2"] = (
        (df["faible_visibilite"] == 1) &
        (
            (df["fragilite_financiere"] == 1) |
            (df["capital_tres_faible"] == 1) |
            (df["depot_non_respecte"] == 1)
        )
    ).astype(int)

    df["no_signal_but_capital_low"] = (
        (df["absence_signal_juridique"] == 1) &
        (df["capital_tres_faible"] == 1)
    ).astype(int)

    df["no_signal_but_no_depot"] = (
        (df["absence_signal_juridique"] == 1) &
        (df["depot_non_respecte"] == 1)
    ).astype(int)

    df["no_signal_but_fragile"] = (
        (df["absence_signal_juridique"] == 1) &
        (df["fragilite_financiere"] == 1)
    ).astype(int)

    # Nouvelle feature forte
    df["super_silent_risk"] = (
        (df["profil_silencieux"] == 1) &
        (df["fragilite_financiere"] == 1)
    ).astype(int)

    # Score financier simple
    df["financial_distress_score"] = (
        (pd.to_numeric(df["bilan_resultat_net"], errors="coerce").fillna(0) < 0).astype(int)
        + (pd.to_numeric(df["bilan_capitaux_propres"], errors="coerce").fillna(0) < 0).astype(int)
        + (df["capital_tres_faible"] == 1).astype(int)
        + (df["depot_non_respecte"] == 1).astype(int)
    )

    return df


df_fe = add_silent_failure_features(df_fe)

print("✅ Features anti-FN renforcées ajoutées")
print(df_fe[[
    "absence_signal_juridique",
    "faible_activite_legale",
    "faible_visibilite",
    "silencieuse_fragile_v2",
    "no_signal_but_capital_low",
    "no_signal_but_no_depot",
    "no_signal_but_fragile",
    "super_silent_risk",
    "financial_distress_score",
]].sum())

"""## 6. Observation date & temporal split

- **Cessées** → `cessation.dateRadiation` (fallback: `reference_date - jours_depuis_update`)
- **Actives** → `reference_date - jours_depuis_update` (proxy)

Rows we cannot date are dropped.
"""

ref_ts = pd.Timestamp(REFERENCE_DATE)
cutoff_ts = pd.Timestamp(TEST_CUTOFF)

# --- 1. observation_date (utilisé pour les diagnostics et l'analyse FN) ----
radiation = pd.to_datetime(df_fe.get('cessation.dateRadiation'), errors='coerce')
days_since_update = pd.to_numeric(df_fe.get('jours_depuis_update'), errors='coerce')
proxy = ref_ts - pd.to_timedelta(days_since_update, unit='D')

obs = np.where(df_fe['target'] == 1, radiation, proxy)
df_fe['observation_date'] = pd.to_datetime(obs, errors='coerce')
fallback = df_fe['observation_date'].isna() & (df_fe['target'] == 1)
df_fe.loc[fallback, 'observation_date'] = proxy.loc[fallback]

# --- 2. Cessées : split TEMPOREL strict par dateRadiation -----------------
ceased = df_fe[df_fe['target'] == 1].copy()
active = df_fe[df_fe['target'] == 0].copy()

# On ne garde que les cessées datables.
ceased = ceased.loc[ceased['observation_date'].notna()].reset_index(drop=True)

ceased_train = ceased[ceased['observation_date'] <  cutoff_ts].reset_index(drop=True)
ceased_test  = ceased[ceased['observation_date'] >= cutoff_ts].reset_index(drop=True)

# --- 3. Actives : split ALÉATOIRE avec le même ratio que les cessées ------
n_ct, n_cs = len(ceased_train), len(ceased_test)
test_frac = n_cs / max(n_ct + n_cs, 1)

active_shuffled = active.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
n_active_test = int(round(len(active_shuffled) * test_frac))
active_test  = active_shuffled.iloc[:n_active_test].reset_index(drop=True)
active_train = active_shuffled.iloc[n_active_test:].reset_index(drop=True)

# --- 4. Concaténation et mélange final -------------------------------------
df_train_full = pd.concat([ceased_train, active_train], ignore_index=True)\
                  .sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
df_test       = pd.concat([ceased_test,  active_test],  ignore_index=True)\
                  .sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

print(f'Cessées train : {n_ct:,}   |  Cessées test : {n_cs:,}   (test_frac={test_frac:.2%})')
print(f'Actives train : {len(active_train):,}   |  Actives test : {len(active_test):,}')
print(f'\nTrain total : {len(df_train_full):,}  '
      f'(cessées={int(df_train_full["target"].sum()):,}, '
      f'actives={int((df_train_full["target"]==0).sum()):,})')
print(f'Test  total : {len(df_test):,}  '
      f'(cessées={int(df_test["target"].sum()):,}, '
      f'actives={int((df_test["target"]==0).sum()):,})')

# --- 5. Validation stratifiée pour early stopping & threshold tuning ------
df_tr, df_va = train_test_split(
    df_train_full, test_size=0.2,
    stratify=df_train_full['target'], random_state=RANDOM_STATE,
)
df_tr = df_tr.reset_index(drop=True)
df_va = df_va.reset_index(drop=True)
print(f'\nInternal: train={len(df_tr):,} (pos={int(df_tr["target"].sum())}) | '
      f'val={len(df_va):,} (pos={int(df_va["target"].sum())})')

# Garde-fou : si l'une des deux classes est absente du train, le fit plantera.
assert df_tr['target'].nunique() == 2, "y_train ne contient qu'une seule classe — vérifie le split."
assert df_va['target'].nunique() == 2, "y_val ne contient qu'une seule classe — vérifie le split."

"""## 7. Feature lists

Two scenarios: `BASELINE` (current model — keeps all features the registry allows) vs `AUDIT` (drops the 5 leaky / suspect features). The honest PR-AUC is the AUDIT one.
"""

# ============================================================
# 7. Feature lists — version corrigée complète
# ============================================================

NUMERIC_FEATURES_ALL = [
    "age_ans",
    "jours_depuis_update",
    "nb_etab_secondaires",
    "nb_etab_fermes",
    "nb_representants_extraits",
    "log_capital",
    "log_capital_safe",

    "nb_annonces_bodacc",
    "flag_procedure_collective",
    "flag_creation_bodacc",
    "flag_depot_comptes",
    "flag_modification_bodacc",

    "nb_observations",
    "nb_observations_critiques",
    "has_alerte_juridique",

    "est_ess",
    "est_micro",
    "est_eirl",
    "est_agricole",
    "est_etranger",
    "multi_etablissement",
    "diffusion_insee",

    "taux_cessation_sectoriel",
    "age_median_sectoriel",
    "secteur_risque_eleve",
    "risque_sectoriel_x_fragilite",

    "has_bilan",
    "bilan_chiffre_affaires",
    "bilan_resultat_net",
    "bilan_capitaux_propres",
    "bilan_total_actif",
    "bilan_marge_nette",
    "bilan_capitaux_negatifs",
    "bilan_resultat_negatif",
    "bilan_ca_absent",
    "bilan_resultat_absent",
    "bilan_capitaux_absents",

    "rentabilite_resultat_sur_ca",
    "solidite_capitaux_sur_actif",
    "capital_sur_actif",
    "marge_nette_faible",
    "marge_nette_negative",
    "fragilite_financiere",
    "fragilite_financiere_sans_alerte",

    "dirigeant_est_judiciaire",
    "dirigeant_est_liquidateur",
    "dirigeant_est_mandataire",
    "dirigeant_age",
    "dirigeant_age_risque",

    "capital_symbolique",
    "capital_tres_faible",
    "capital_absent",
    "depot_non_respecte",

    "frequence_bodacc",
    "frequence_observations",
    "frequence_observations_critiques",
    "ratio_observations_critiques",
    "ratio_etab_fermes",
    "a_ferme_etablissement",

    "representants_peu_nombreux",
    "profil_silencieux",
    "silencieux_mais_fragile",
    "jeune_silencieuse_fragile",
    "ancienne_silencieuse_fragile",

    "juridique_x_financier",
    "bodacc_x_financier",
    "secteur_x_financier",

    "jeune_secteur_risque",
    "ancienne_inactive",
    "micro_sans_capital",

    # nouvelles features anti-FN
    "absence_signal_juridique",
    "faible_activite_legale",
    "faible_visibilite",
    "silencieuse_fragile_v2",
    "no_signal_but_capital_low",
    "no_signal_but_no_depot",
    "no_signal_but_fragile",
    "super_silent_risk",
    "financial_distress_score",
]

CATEGORICAL_FEATURES = [
    "forme_juridique_lib",
    "secteur_naf2",
    "stade_vie",
    "forme_juridique_risque",
    "departement",
]

available = set(df_fe.columns)

NUMERIC_FEATURES_ALL = [c for c in NUMERIC_FEATURES_ALL if c in available]
CATEGORICAL_FEATURES = [c for c in CATEGORICAL_FEATURES if c in available]

NUMERIC_FEATURES_AUDIT = [
    c for c in NUMERIC_FEATURES_ALL
    if c not in LEAKY_FEATURES
]

print(f"BASELINE numeric : {len(NUMERIC_FEATURES_ALL)} features")
print(f"AUDIT numeric    : {len(NUMERIC_FEATURES_AUDIT)} features")
print(f"Dropped leakage  : {sorted(set(NUMERIC_FEATURES_ALL) - set(NUMERIC_FEATURES_AUDIT))}")
print(f"Categorical      : {CATEGORICAL_FEATURES}")

"""## 8. Preprocessor

Same preprocessing for all three boosters so the comparison is fair: median-impute numerics, ordinal-encode categoricals (handles unseen categories at inference time).
"""

def make_preprocessor(numeric_features, categorical_features):
    num = Pipeline([('impute', SimpleImputer(strategy='median'))])
    cat = Pipeline([
        ('impute', SimpleImputer(strategy='constant', fill_value='__missing__')),
        ('encode', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
    ])
    return ColumnTransformer([
        ('num', num, numeric_features),
        ('cat', cat, categorical_features),
    ], remainder='drop', verbose_feature_names_out=False)

def to_xy(df, numeric_features, categorical_features):
    X = df[numeric_features + categorical_features].copy()
    for c in categorical_features:
        X[c] = X[c].astype(object)
    y = df['target'].to_numpy()
    return X, y

"""## 9. Model factories"""

def scale_pos_weight(y):
    n_pos = int((y == 1).sum())
    n_neg = int((y == 0).sum())
    return n_neg / max(n_pos, 1)

def make_xgb(spw):
    return xgb.XGBClassifier(
        n_estimators=1000, learning_rate=0.05, max_depth=5,
        min_child_weight=3, subsample=0.85, colsample_bytree=0.85,
        reg_lambda=1.0, gamma=0.0, tree_method='hist',
        scale_pos_weight=spw, random_state=RANDOM_STATE,
        eval_metric='aucpr', early_stopping_rounds=50, n_jobs=-1, verbosity=0,
    )

def make_lgbm(spw):
    return lgb.LGBMClassifier(
        n_estimators=2000, learning_rate=0.05, num_leaves=31, max_depth=-1,
        min_child_samples=20, subsample=0.85, colsample_bytree=0.85,
        reg_lambda=1.0, scale_pos_weight=spw, random_state=RANDOM_STATE,
        n_jobs=-1, verbose=-1,
    )

def make_catboost(spw):
    return cb.CatBoostClassifier(
        iterations=2000, learning_rate=0.05, depth=6, l2_leaf_reg=3.0,
        scale_pos_weight=spw, random_seed=RANDOM_STATE,
        eval_metric='PRAUC', early_stopping_rounds=50,
        verbose=False, allow_writing_files=False,
    )

"""## 10. Unified training loop

Trains a model with early stopping on the validation set, then returns the fitted preprocessor + estimator and the validation score curve.

**Important:** the preprocessor is fit on `df_tr` only — no information leaks from `df_va` or `df_test` into encoding.
"""

# ============================================================
# 10. Unified training loop — avec sample_weight anti-FN
# ============================================================

def build_sample_weight(df_train):
    w = np.ones(len(df_train), dtype=float)

    # Booster les cessées silencieuses/fragles
    mask_silent_failure = (
        (df_train["target"] == 1) &
        (
            (df_train.get("silencieux_mais_fragile", 0) == 1) |
            (df_train.get("silencieuse_fragile_v2", 0) == 1) |
            (df_train.get("super_silent_risk", 0) == 1)
        )
    )

    w[mask_silent_failure] = 4.0

    return w


def fit_model(name, df_tr, df_va, numeric_features, categorical_features):
    pre = make_preprocessor(numeric_features, categorical_features)

    X_tr_raw, y_tr = to_xy(df_tr, numeric_features, categorical_features)
    X_va_raw, y_va = to_xy(df_va, numeric_features, categorical_features)

    pre.fit(X_tr_raw)

    X_tr = pre.transform(X_tr_raw)
    X_va = pre.transform(X_va_raw)

    spw = scale_pos_weight(y_tr)
    sample_weight = build_sample_weight(df_tr)

    if name == "xgboost":
        model = make_xgb(spw)
        model.fit(
            X_tr,
            y_tr,
            sample_weight=sample_weight,
            eval_set=[(X_va, y_va)],
            verbose=False
        )

    elif name == "lightgbm":
        model = make_lgbm(spw)
        model.fit(
            X_tr,
            y_tr,
            sample_weight=sample_weight,
            eval_set=[(X_va, y_va)],
            eval_metric="average_precision",
            callbacks=[lgb.early_stopping(50, verbose=False)],
        )

    elif name == "catboost":
        model = make_catboost(spw)
        model.fit(
            X_tr,
            y_tr,
            sample_weight=sample_weight,
            eval_set=(X_va, y_va),
            verbose=False
        )

    else:
        raise ValueError(name)

    return {
        "name": name,
        "preprocessor": pre,
        "model": model,
        "numeric_features": list(numeric_features),
        "categorical_features": list(categorical_features),
        "feature_names_out": list(numeric_features) + list(categorical_features),
    }


def predict_proba(bundle, df):
    X_raw, y = to_xy(
        df,
        bundle["numeric_features"],
        bundle["categorical_features"]
    )

    X = bundle["preprocessor"].transform(X_raw)
    proba = bundle["model"].predict_proba(X)[:, 1]

    return proba, y

"""## 11. Metrics"""

def compute_metrics(y_true, y_proba, threshold=0.5):
    y_pred = (y_proba >= threshold).astype(int)
    return {
        'roc_auc'   : roc_auc_score(y_true, y_proba),
        'pr_auc'    : average_precision_score(y_true, y_proba),
        'brier'     : brier_score_loss(y_true, y_proba),
        'precision' : precision_score(y_true, y_pred, zero_division=0),
        'recall'    : recall_score(y_true, y_pred, zero_division=0),
        'f1'        : f1_score(y_true, y_pred, zero_division=0),
        'threshold' : threshold,
        'n_pos'     : int((y_true == 1).sum()),
        'n_neg'     : int((y_true == 0).sum()),
    }

"""## 12. The leakage audit

Train each model **twice**: once with the leaky features included (BASELINE — what your current pipeline does), once without (AUDIT — the honest version). Display the delta.

If PR-AUC barely changes, the leaky features were not load-bearing. If PR-AUC drops sharply, they were leaking the label.
"""

# ============================================================
# 12. Leakage audit — comparaison baseline vs audit
# ============================================================

MODEL_NAMES = ["xgboost", "lightgbm", "catboost"]

scenarios = {
    "BASELINE": NUMERIC_FEATURES_ALL,
    "AUDIT": NUMERIC_FEATURES_AUDIT,
}

bundles = {}
metrics_rows = []

for scenario, numeric_features in scenarios.items():
    print("\n" + "=" * 70)
    print(f"SCENARIO : {scenario}")
    print("=" * 70)

    for name in MODEL_NAMES:
        print(f" → Training {scenario:9s} {name}")

        b = fit_model(
            name,
            df_tr,
            df_va,
            numeric_features,
            CATEGORICAL_FEATURES
        )

        bundles[(scenario, name)] = b

        proba_va, y_va_tmp = predict_proba(b, df_va)
        proba_te, y_te_tmp = predict_proba(b, df_test)

        m_va = compute_metrics(y_va_tmp, proba_va, threshold=0.5)
        m_te = compute_metrics(y_te_tmp, proba_te, threshold=0.5)

        metrics_rows.append({
            "scenario": scenario,
            "model": name,
            "split": "val",
            **m_va
        })

        metrics_rows.append({
            "scenario": scenario,
            "model": name,
            "split": "test",
            **m_te
        })

metrics_df = pd.DataFrame(metrics_rows)

test_only = metrics_df[metrics_df["split"] == "test"].pivot(
    index="model",
    columns="scenario",
    values=["roc_auc", "pr_auc", "recall", "precision", "f1", "brier"]
)

print("\n=== TEST-set metrics: BASELINE vs AUDIT ===")
display(test_only.round(4))

delta = (
    test_only.xs("BASELINE", axis=1, level=1)
    - test_only.xs("AUDIT", axis=1, level=1)
).round(4)

delta.columns = [f"{c}_delta_baseline_minus_audit" for c in delta.columns]

print("\n=== DELTA : impact des features suspectes ===")
display(delta)

print("\nLecture :")
print("- delta PR-AUC > 0.05  : forte suspicion de leakage utile au modèle")
print("- delta PR-AUC < 0.02  : les features retirées ne portaient pas beaucoup le score")
print("- delta négatif        : retirer ces features a amélioré la généralisation")

"""**Reading the table:**
- `pr_auc_delta_baseline_minus_audit > 0.05` → meaningful leakage. Trust the AUDIT row.
- `pr_auc_delta_baseline_minus_audit < 0.02` → the leaky-flagged features were not driving the score; the BASELINE was honest.

Everything below this point uses the **AUDIT** scenario — the honest pipeline.

## 13. Pick the winner & calibrate

Best AUDIT model by **PR-AUC on the held-out 2023 test set**. Calibration: isotonic, fit on the validation slice (prefit) so probabilities mean what they say.
"""

# ============================================================
# 13. Pick the winner — SANS calibration isotonic
# ============================================================

audit_test = metrics_df[
    (metrics_df["scenario"] == "AUDIT") &
    (metrics_df["split"] == "test")
].copy()

print("=== Résultats AUDIT sur test ===")
display(
    audit_test[[
        "model", "roc_auc", "pr_auc", "precision", "recall", "f1", "brier"
    ]]
    .sort_values("pr_auc", ascending=False)
    .round(4)
)

audit_test = audit_test.sort_values(
    ["pr_auc", "f1", "recall"],
    ascending=[False, False, False]
)

winner = audit_test.iloc[0]["model"]
print(f"\n🏆 Winner AUDIT : {winner}")

win = bundles[("AUDIT", winner)]

X_va_raw, y_va = to_xy(
    df_va,
    win["numeric_features"],
    win["categorical_features"]
)

X_te_raw, y_te = to_xy(
    df_test,
    win["numeric_features"],
    win["categorical_features"]
)

X_va_mat = win["preprocessor"].transform(X_va_raw)
X_te_mat = win["preprocessor"].transform(X_te_raw)

# ============================================================
# IMPORTANT :
# Pas de calibration isotonic ici.
# Elle a dégradé le recall et augmenté les faux négatifs.
# On garde donc la probabilité RAW du modèle.
# ============================================================

USE_CALIBRATED_SCORE = False
score_source = "raw_probability"

proba_va_final = win["model"].predict_proba(X_va_mat)[:, 1]
proba_te_final = win["model"].predict_proba(X_te_mat)[:, 1]

winner_summary = pd.DataFrame([{
    "winner": winner,
    "roc_auc_test": roc_auc_score(y_te, proba_te_final),
    "pr_auc_test": average_precision_score(y_te, proba_te_final),
    "brier_test": brier_score_loss(y_te, proba_te_final),
    "score_source": score_source,
}])

print("\n=== Winner final SANS calibration ===")
display(winner_summary.round(4))

print("\n✅ Cellule 13 terminée.")
print(f"Modèle final candidat : {winner}")
print(f"Score source : {score_source}")
print(f"USE_CALIBRATED_SCORE : {USE_CALIBRATED_SCORE}")
print(f"X_va_mat shape : {X_va_mat.shape}")
print(f"X_te_mat shape : {X_te_mat.shape}")

"""## 14. Threshold optimization

Two strategies:
1. **Recall constraint** — your current rule: pick the threshold maximizing F1 subject to `recall ≥ MIN_RECALL`.
2. **Cost-sensitive** — minimize `FP·COST_FP + FN·COST_FN` directly. This is the business-aligned choice when you can quantify costs.
"""

# ============================================================
# 14. Threshold optimization — réduire FP sans exploser FN
# ============================================================

def evaluate_threshold(name, threshold, y_true, proba):
    y_pred = (proba >= threshold).astype(int)

    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())

    return {
        "strategy": name,
        "threshold": threshold,
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1": f1_score(y_true, y_pred, zero_division=0),
        "TP": tp,
        "FN": fn,
        "FP": fp,
        "TN": tn,
        "business_cost": fn * COST_FN + fp * COST_FP,
    }


threshold_grid = np.round(np.arange(0.02, 0.151, 0.005), 3)

thr_df = pd.DataFrame([
    evaluate_threshold(f"thr_{t:.3f}", t, y_te, proba_te_final)
    for t in threshold_grid
])

print("=== Threshold comparison — réduction FP ===")
display(thr_df.sort_values("threshold").round(4))

# Objectif : garder FN bas mais réduire FP
# Tu peux ajuster cette limite selon ton métier.
MAX_FN_ALLOWED = 50

candidate_df = thr_df[thr_df["FN"] <= MAX_FN_ALLOWED].copy()

if len(candidate_df) > 0:
    best_row = candidate_df.sort_values(["FP", "business_cost"]).iloc[0]
    print(f"✅ Seuil trouvé avec FN <= {MAX_FN_ALLOWED}")
else:
    best_row = thr_df.sort_values(["FN", "FP"]).iloc[0]
    print(f"⚠️ Aucun seuil avec FN <= {MAX_FN_ALLOWED}, meilleur compromis choisi.")

FINAL_THRESHOLD = float(best_row["threshold"])

print("\n✅ Seuil final proposé:")
display(pd.DataFrame([best_row]).round(4))

"""## 15. Final test report at the chosen threshold

We pick the **recall-constrained** threshold to match your business priority (don't miss failing companies). Confusion matrix + classification report below.
"""

# ============================================================
# 15. Final test report — seuil FP-friendly
# ============================================================

y_te_pred = (proba_te_final >= FINAL_THRESHOLD).astype(int)

cm = confusion_matrix(y_te, y_te_pred)

print(f"Final threshold utilisé : {FINAL_THRESHOLD:.4f}")

print("\nConfusion matrix:")
print(pd.DataFrame(
    cm,
    index=["actual_active", "actual_cessée"],
    columns=["pred_active", "pred_cessée"]
))

print("\nClassification report:")
print(classification_report(
    y_te,
    y_te_pred,
    target_names=["active", "cessée"],
    digits=4
))

tp = int(((y_te == 1) & (y_te_pred == 1)).sum())
fn = int(((y_te == 1) & (y_te_pred == 0)).sum())
fp = int(((y_te == 0) & (y_te_pred == 1)).sum())
tn = int(((y_te == 0) & (y_te_pred == 0)).sum())

print("\nRésumé métier:")
print(f"Vraies cessées détectées : {tp:,} / {(y_te == 1).sum():,}")
print(f"Cessées ratées FN        : {fn:,}")
print(f"Fausses alertes FP       : {fp:,}")
print(f"Recall cessée            : {recall_score(y_te, y_te_pred):.4f}")
print(f"Precision cessée         : {precision_score(y_te, y_te_pred):.4f}")
print(f"F1 cessée                : {f1_score(y_te, y_te_pred):.4f}")
print(f"Coût métier              : {fn * COST_FN + fp * COST_FP:,.0f}")

print("\nScores globaux:")
print(f"ROC-AUC : {roc_auc_score(y_te, proba_te_final):.4f}")
print(f"PR-AUC  : {average_precision_score(y_te, proba_te_final):.4f}")

# ============================================================
# 15bis. Hybrid decision layer — V5
# Objectif :
# - garder l'amélioration FN de V4
# - réduire le bruit FP de rule_silent_recovery
# ============================================================

df_te_hybrid = df_test.copy().reset_index(drop=True)
df_te_hybrid["proba"] = proba_te_final
df_te_hybrid["target"] = y_te

# ------------------------------------------------------------
# 1. Prédiction ML large
# ------------------------------------------------------------
df_te_hybrid["ml_alert"] = (df_te_hybrid["proba"] >= FINAL_THRESHOLD).astype(int)

# ------------------------------------------------------------
# 2. Sécuriser les colonnes nécessaires
# ------------------------------------------------------------
needed_cols = [
    "has_alerte_juridique",
    "nb_observations",
    "nb_observations_critiques",
    "nb_annonces_bodacc",
    "nb_etab_fermes",
    "fragilite_financiere",
    "fragilite_financiere_sans_alerte",
    "depot_non_respecte",
    "capital_tres_faible",
    "profil_silencieux",
    "silencieux_mais_fragile",
    "silencieuse_fragile_v2",
    "ancienne_silencieuse_fragile",
    "super_silent_risk",
    "financial_distress_score",
]

for col in needed_cols:
    if col not in df_te_hybrid.columns:
        df_te_hybrid[col] = 0

# ------------------------------------------------------------
# 3. Score de confirmation métier
# ------------------------------------------------------------
df_te_hybrid["business_confirmation_score"] = (
    (df_te_hybrid["has_alerte_juridique"] == 1).astype(int) * 3
    + (df_te_hybrid["nb_observations_critiques"] >= 1).astype(int) * 2
    + (df_te_hybrid["nb_etab_fermes"] >= 1).astype(int) * 2
    + (df_te_hybrid["fragilite_financiere"] == 1).astype(int) * 2
    + (df_te_hybrid["fragilite_financiere_sans_alerte"] == 1).astype(int) * 2
    + (df_te_hybrid["depot_non_respecte"] == 1).astype(int) * 1
    + (df_te_hybrid["capital_tres_faible"] == 1).astype(int) * 1
    + (df_te_hybrid["super_silent_risk"] == 1).astype(int) * 3
    + (df_te_hybrid["silencieux_mais_fragile"] == 1).astype(int) * 2
    + (df_te_hybrid["financial_distress_score"] >= 2).astype(int) * 2
)
# Score lisible produit (0–100)
df_te_hybrid["risk_score"] = (df_te_hybrid["proba"] * 100).round(1)

# Niveau de risque business
df_te_hybrid["risk_level"] = pd.cut(
    df_te_hybrid["proba"],
    bins=[0, 0.03, 0.06, 0.10, 1],
    labels=["Faible", "Modéré", "Élevé", "Critique"]
)

# ------------------------------------------------------------
# 4. Filtres anti-FP
# ------------------------------------------------------------
df_te_hybrid["clean_profile"] = (
    (df_te_hybrid["has_alerte_juridique"] == 0)
    & (df_te_hybrid["nb_observations_critiques"] == 0)
    & (df_te_hybrid["fragilite_financiere"] == 0)
    & (df_te_hybrid["nb_annonces_bodacc"] <= 1)
).astype(int)

df_te_hybrid["weak_signal"] = (
    (df_te_hybrid["nb_annonces_bodacc"] <= 1)
    & (df_te_hybrid["nb_observations"] <= 1)
    & (df_te_hybrid["fragilite_financiere"] == 0)
).astype(int)

df_te_hybrid["medium_risk_noise"] = (
    (df_te_hybrid["nb_observations_critiques"] == 0)
    & (df_te_hybrid["has_alerte_juridique"] == 0)
    & (df_te_hybrid["nb_annonces_bodacc"] <= 2)
    & (df_te_hybrid["fragilite_financiere"] == 0)
).astype(int)

# ------------------------------------------------------------
# 5. Règles V5
# ------------------------------------------------------------
HIGH_RISK_THRESHOLD = 0.10
LOW_RISK_THRESHOLD = FINAL_THRESHOLD
MIN_CONFIRMATION_SCORE = 4

rule_high_proba = df_te_hybrid["proba"] >= HIGH_RISK_THRESHOLD

rule_gray_confirmed = (
    (df_te_hybrid["proba"] >= LOW_RISK_THRESHOLD)
    & (df_te_hybrid["business_confirmation_score"] >= MIN_CONFIRMATION_SCORE)
    & (
        (df_te_hybrid["proba"] >= 0.06)
        | (df_te_hybrid["business_confirmation_score"] >= 6)
    )
)

# V5 : récupération silencieuse plus stricte que V4
rule_silent_recovery = (
    (df_te_hybrid["proba"] >= 0.045)
    & (
        (df_te_hybrid["super_silent_risk"] == 1)
        | (df_te_hybrid["silencieuse_fragile_v2"] == 1)
        | (df_te_hybrid["ancienne_silencieuse_fragile"] == 1)
    )
    & (
        (df_te_hybrid["financial_distress_score"] >= 2)
        | (df_te_hybrid["depot_non_respecte"] == 1)
        | (df_te_hybrid["capital_tres_faible"] == 1)
    )
    & (df_te_hybrid["nb_annonces_bodacc"] <= 2)
)

rule_not_clean_noise = (
    (df_te_hybrid["clean_profile"] == 0)
    | (df_te_hybrid["super_silent_risk"] == 1)
    | (df_te_hybrid["financial_distress_score"] >= 2)
)

df_te_hybrid["hybrid_pred"] = (
    (
        rule_high_proba
        | rule_gray_confirmed
        | rule_silent_recovery
    )
    & rule_not_clean_noise
).astype(int)

# ------------------------------------------------------------
# 6. Évaluation
# ------------------------------------------------------------
tp = int(((df_te_hybrid["target"] == 1) & (df_te_hybrid["hybrid_pred"] == 1)).sum())
fn = int(((df_te_hybrid["target"] == 1) & (df_te_hybrid["hybrid_pred"] == 0)).sum())
fp = int(((df_te_hybrid["target"] == 0) & (df_te_hybrid["hybrid_pred"] == 1)).sum())
tn = int(((df_te_hybrid["target"] == 0) & (df_te_hybrid["hybrid_pred"] == 0)).sum())

print("=== Hybrid ML + règles métier optimisé V5 ===")
print(pd.DataFrame(
    [[tn, fp], [fn, tp]],
    index=["actual_active", "actual_cessée"],
    columns=["pred_active", "pred_cessée"]
))

print("\nRésumé hybride optimisé V5:")
print(f"TP : {tp}")
print(f"FN : {fn}")
print(f"FP : {fp}")
print(f"TN : {tn}")
print(f"Recall cessée    : {recall_score(df_te_hybrid['target'], df_te_hybrid['hybrid_pred']):.4f}")
print(f"Precision cessée : {precision_score(df_te_hybrid['target'], df_te_hybrid['hybrid_pred']):.4f}")
print(f"F1 cessée        : {f1_score(df_te_hybrid['target'], df_te_hybrid['hybrid_pred']):.4f}")
print(f"Coût métier      : {fn * COST_FN + fp * COST_FP:,.0f}")

# ------------------------------------------------------------
# 7. Comparaison
# ------------------------------------------------------------
ml_fn = int(((y_te == 1) & (y_te_pred == 0)).sum())
ml_fp = int(((y_te == 0) & (y_te_pred == 1)).sum())

print("\nComparaison:")
print(f"ML seul    -> FN={ml_fn}, FP={ml_fp}")
print(f"Hybride V5 -> FN={fn}, FP={fp}")

# ------------------------------------------------------------
# 8. Diagnostic des règles
# ------------------------------------------------------------
df_te_hybrid["rule_high_proba"] = rule_high_proba.astype(int)
df_te_hybrid["rule_gray_confirmed"] = rule_gray_confirmed.astype(int)
df_te_hybrid["rule_silent_recovery"] = rule_silent_recovery.astype(int)
df_te_hybrid["rule_not_clean_noise"] = rule_not_clean_noise.astype(int)

print("\nActivation des règles:")
print(df_te_hybrid[[
    "rule_high_proba",
    "rule_gray_confirmed",
    "rule_silent_recovery",
    "rule_not_clean_noise",
]].sum())

preview_cols = [
    "target",
    "proba",
    "ml_alert",
    "hybrid_pred",
    "business_confirmation_score",
    "rule_high_proba",
    "rule_gray_confirmed",
    "rule_silent_recovery",
    "clean_profile",
    "weak_signal",
    "medium_risk_noise",
    "has_alerte_juridique",
    "nb_observations",
    "nb_observations_critiques",
    "nb_annonces_bodacc",
    "fragilite_financiere",
    "depot_non_respecte",
    "capital_tres_faible",
    "super_silent_risk",
    "financial_distress_score",
]

preview_cols = [c for c in preview_cols if c in df_te_hybrid.columns]

display(df_te_hybrid[preview_cols].head(20))

# ============================================================
# 15ter-1. Calibration sigmoid — CatBoost AUDIT final
# ============================================================

from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.metrics import log_loss, brier_score_loss

print("🔧 Calibration sigmoid du modèle final CatBoost...")

try:
    calibrator_sigmoid = CalibratedClassifierCV(
        estimator=win["model"],
        method="sigmoid",
        cv="prefit"
    )
except TypeError:
    calibrator_sigmoid = CalibratedClassifierCV(
        base_estimator=win["model"],
        method="sigmoid",
        cv="prefit"
    )

calibrator_sigmoid.fit(X_va_mat, y_va)

proba_va_calibrated = calibrator_sigmoid.predict_proba(X_va_mat)[:, 1]
proba_te_calibrated = calibrator_sigmoid.predict_proba(X_te_mat)[:, 1]

print("✅ Calibration terminée.")

# ============================================================
# 15ter-2. Comparaison RAW vs CALIBRATED + choix final
# ============================================================

calibration_compare = pd.DataFrame([
    {
        "version": "raw",
        "roc_auc": roc_auc_score(y_te, proba_te_final),
        "pr_auc": average_precision_score(y_te, proba_te_final),
        "brier": brier_score_loss(y_te, proba_te_final),
        "log_loss": log_loss(y_te, proba_te_final),
    },
    {
        "version": "sigmoid_calibrated",
        "roc_auc": roc_auc_score(y_te, proba_te_calibrated),
        "pr_auc": average_precision_score(y_te, proba_te_calibrated),
        "brier": brier_score_loss(y_te, proba_te_calibrated),
        "log_loss": log_loss(y_te, proba_te_calibrated),
    }
])

display(calibration_compare.round(4))

raw_brier = calibration_compare.loc[
    calibration_compare["version"] == "raw", "brier"
].iloc[0]

cal_brier = calibration_compare.loc[
    calibration_compare["version"] == "sigmoid_calibrated", "brier"
].iloc[0]

raw_logloss = calibration_compare.loc[
    calibration_compare["version"] == "raw", "log_loss"
].iloc[0]

cal_logloss = calibration_compare.loc[
    calibration_compare["version"] == "sigmoid_calibrated", "log_loss"
].iloc[0]

raw_pr = calibration_compare.loc[
    calibration_compare["version"] == "raw", "pr_auc"
].iloc[0]

cal_pr = calibration_compare.loc[
    calibration_compare["version"] == "sigmoid_calibrated", "pr_auc"
].iloc[0]


# ✅ Règle propre :
# On utilise la calibration seulement si elle améliore Brier ET LogLoss,
# sans dégrader fortement PR-AUC.
if (cal_brier < raw_brier) and (cal_logloss < raw_logloss) and (cal_pr >= raw_pr - 0.02):
    USE_CALIBRATED_SCORE = True
    proba_score_final = proba_te_calibrated
    score_source = "sigmoid_calibrated"
    print("✅ Calibration retenue pour le score final.")
else:
    USE_CALIBRATED_SCORE = False
    proba_score_final = proba_te_final
    score_source = "raw_probability"
    print("⚠️ Calibration non retenue : on garde la probabilité RAW.")

print(f"\nUSE_CALIBRATED_SCORE = {USE_CALIBRATED_SCORE}")
print(f"score_source = {score_source}")

# ============================================================
# 15ter-3. Courbe de calibration RAW vs CALIBRATED
# ============================================================

plt.figure(figsize=(7, 6))

for label, proba in [
    ("raw", proba_te_final),
    ("sigmoid_calibrated", proba_te_calibrated),
]:
    prob_true, prob_pred = calibration_curve(
        y_te,
        proba,
        n_bins=10,
        strategy="quantile"
    )

    plt.plot(prob_pred, prob_true, marker="o", label=label)

plt.plot([0, 1], [0, 1], "--", label="perfect calibration")

plt.title("Calibration curve — CatBoost")
plt.xlabel("Probabilité prédite")
plt.ylabel("Fréquence réelle de cessation")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 15ter-4. Score final 0–100
# ============================================================

df_te_hybrid["proba_score_final"] = proba_score_final
df_te_hybrid["score_source"] = score_source

df_te_hybrid["risk_score"] = (
    df_te_hybrid["proba_score_final"] * 100
).round(1)

def risk_level_fr(score):
    if score >= 75:
        return "Risque très élevé"
    elif score >= 50:
        return "Risque élevé"
    elif score >= 30:
        return "Risque modéré"
    else:
        return "Faible risque"

df_te_hybrid["risk_level"] = df_te_hybrid["risk_score"].apply(risk_level_fr)

print("✅ Score final créé.")
print(f"Score source : {score_source}")
print(f"USE_CALIBRATED_SCORE : {USE_CALIBRATED_SCORE}")

display(df_te_hybrid[[
    "target",
    "proba",
    "proba_score_final",
    "risk_score",
    "risk_level",
    "hybrid_pred",
    "score_source"
]].head(20))

"""## 16. False negative analysis

Inspect every cessation the model failed to flag. Compare their feature distributions against true positives, then cluster them to surface failure modes.
"""

# ============================================================
# 16. False negative analysis — avec seuil final corrigé
# ============================================================

df_te_with_pred = df_test.copy().reset_index(drop=True)

df_te_with_pred["proba"] = proba_te_final
df_te_with_pred["predicted"] = y_te_pred

fn_mask = (df_te_with_pred["target"] == 1) & (df_te_with_pred["predicted"] == 0)
tp_mask = (df_te_with_pred["target"] == 1) & (df_te_with_pred["predicted"] == 1)

df_fn = df_te_with_pred[fn_mask].copy()
df_tp = df_te_with_pred[tp_mask].copy()

print(f"False negatives: {len(df_fn)} | True positives: {len(df_tp)}")

compare_cols = [c for c in win["numeric_features"] if c in df_te_with_pred.columns]

comp = pd.DataFrame({
    "fn_median": df_fn[compare_cols].median(numeric_only=True),
    "tp_median": df_tp[compare_cols].median(numeric_only=True),
    "fn_mean": df_fn[compare_cols].mean(numeric_only=True),
    "tp_mean": df_tp[compare_cols].mean(numeric_only=True),
})

comp["gap"] = (comp["fn_median"] - comp["tp_median"]).abs()

print("\nLargest FN-vs-TP median gaps:")
display(comp.sort_values("gap", ascending=False).head(20).round(3))

if len(df_fn) >= 6:
    X_fn_raw, _ = to_xy(
        df_fn,
        win["numeric_features"],
        win["categorical_features"]
    )

    X_fn = win["preprocessor"].transform(X_fn_raw)

    k = min(3, len(df_fn) // 2)

    km = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=10
    ).fit(X_fn)

    df_fn["cluster"] = km.labels_

    print(f"\nFN cluster sizes (k={k}):")
    print(df_fn["cluster"].value_counts().sort_index())

    cluster_summary = (
        df_fn
        .groupby("cluster")[compare_cols]
        .median(numeric_only=True)
        .round(3)
    )

    print("\nFN cluster medians:")
    display(cluster_summary)
else:
    print("\nNot enough FN to cluster meaningfully (< 6).")

# ============================================================
# 16 BIS — Analyse experte des faux négatifs (niveau expert)
# ============================================================

print("🔍 ANALYSE APPROFONDIE DES FAUX NÉGATIFS")

# --- 1. Comparaison FN vs TP (moyennes) ----------------------

important_cols = [
    "age_ans",
    "nb_annonces_bodacc",
    "nb_observations",
    "nb_observations_critiques",
    "has_alerte_juridique",
    "capital_tres_faible",
    "depot_non_respecte",
    "fragilite_financiere",
    "profil_silencieux",
    "silencieux_mais_fragile",
    "bilan_resultat_net",
    "bilan_capitaux_propres",
]

important_cols = [c for c in important_cols if c in df_fn.columns]

comparison = pd.DataFrame({
    "FN_mean": df_fn[important_cols].mean(numeric_only=True),
    "TP_mean": df_tp[important_cols].mean(numeric_only=True),
})

comparison["gap"] = (comparison["FN_mean"] - comparison["TP_mean"]).abs()

print("\n📊 Différences FN vs TP (les plus importantes):")
display(comparison.sort_values("gap", ascending=False).head(15))


# --- 2. Distribution des probabilités FN ---------------------

print("\n📉 Distribution des probabilités des FN:")
display(df_fn["proba"].describe())

plt.hist(df_fn["proba"], bins=20)
plt.title("Distribution des probabilités des faux négatifs")
plt.xlabel("proba")
plt.ylabel("count")
plt.show()


# --- 3. Analyse secteur --------------------------------------

if "secteur_naf2" in df_fn.columns:
    print("\n🏭 Secteurs les plus présents dans FN:")
    display(df_fn["secteur_naf2"].value_counts().head(10))


# --- 4. Analyse département ----------------------------------

if "departement" in df_fn.columns:
    print("\n📍 Départements des FN:")
    display(df_fn["departement"].value_counts().head(10))


# --- 5. Cas typiques FN --------------------------------------

print("\n🧠 Exemple de faux négatifs (cas typiques):")
display(df_fn.sort_values("proba").head(10)[[
    c for c in [
        "age_ans",
        "nb_annonces_bodacc",
        "nb_observations",
        "has_alerte_juridique",
        "fragilite_financiere",
        "profil_silencieux",
        "proba"
    ] if c in df_fn.columns
]])

# ============================================================
# ÉTAPE 1 — Diagnostic détaillé des faux négatifs
# ============================================================

print("Nombre FN:", len(df_fn))
print("Nombre TP:", len(df_tp))

diagnostic_cols = [
    "siren",
    "denomination",
    "age_ans",
    "secteur_naf2",
    "departement",
    "forme_juridique_lib",
    "nb_annonces_bodacc",
    "nb_observations",
    "nb_observations_critiques",
    "has_alerte_juridique",
    "nb_etab_fermes",
    "flag_depot_comptes",
    "depot_non_respecte",
    "log_capital_safe",
    "capital_tres_faible",
    "bilan_resultat_net",
    "bilan_capitaux_propres",
    "bilan_marge_nette",
    "fragilite_financiere",
    "profil_silencieux",
    "silencieux_mais_fragile",
    "proba"
]

diagnostic_cols = [c for c in diagnostic_cols if c in df_fn.columns]

print("\nAperçu des faux négatifs avec proba la plus haute :")
display(
    df_fn.sort_values("proba", ascending=False)[diagnostic_cols].head(20)
)

print("\nAperçu des faux négatifs avec proba la plus basse :")
display(
    df_fn.sort_values("proba", ascending=True)[diagnostic_cols].head(20)
)

print("\nRésumé FN:")
display(df_fn[diagnostic_cols].describe(include="all").T)

"""## 17. SHAP explanations

TreeExplainer on the winning model (uncalibrated — SHAP needs raw tree outputs). Calibration affects the displayed probability but not the relative attribution.

**Note on departement:** if SHAP shows it as a top contributor, run a permutation-importance + drop-column check to confirm the contribution is real (the cell after this one).
"""

# ============================================================
# 17. SHAP explanations + permutation importance
# ============================================================

perm = permutation_importance(
    win["model"],
    X_te_mat,
    y_te,
    n_repeats=10,
    random_state=RANDOM_STATE,
    scoring="average_precision",
    n_jobs=-1,
)

perm_df = pd.DataFrame({
    "feature": win["feature_names_out"],
    "importance_mean": perm.importances_mean,
    "importance_std": perm.importances_std,
}).sort_values("importance_mean", ascending=False)

print("Permutation importance (PR-AUC drop on test when shuffled):")
display(perm_df.head(25).round(4))

print("\nCalcul SHAP...")

feature_names = win["feature_names_out"]

explainer = shap.TreeExplainer(win["model"])
raw_shap_values = explainer.shap_values(X_te_mat)

if isinstance(raw_shap_values, list):
    shap_values = raw_shap_values[1]
else:
    shap_values = raw_shap_values

shap_values = np.array(shap_values)

print("✅ SHAP calculé")
print("Shape shap_values:", shap_values.shape)
print("Shape X_te_mat:", X_te_mat.shape)

# Permutation importance sur le test, directement sur la matrice transformée
# (X_te_mat a été créé en section 13). Plus simple et plus rapide que de
# passer par un wrapper raw → preprocess → model.
perm = permutation_importance(
    win['model'], X_te_mat, y_te,
    n_repeats=10, random_state=RANDOM_STATE,
    scoring='average_precision', n_jobs=-1,
)
perm_df = pd.DataFrame({
    'feature'        : win['feature_names_out'],
    'importance_mean': perm.importances_mean,
    'importance_std' : perm.importances_std,
}).sort_values('importance_mean', ascending=False)
print('Permutation importance (PR-AUC drop on test when shuffled):')
display(perm_df.head(20).round(4))

# ============================================================
# SHAP VALUES — à exécuter avant les explications françaises
# ============================================================

print("Calcul SHAP...")

feature_names = win["feature_names_out"]

# X_te_mat existe déjà depuis la section calibration
explainer = shap.TreeExplainer(win["model"])

raw_shap_values = explainer.shap_values(X_te_mat)

# Selon le modèle / version SHAP, le format peut changer
if isinstance(raw_shap_values, list):
    shap_values = raw_shap_values[1]  # classe positive = cessée
else:
    shap_values = raw_shap_values

shap_values = np.array(shap_values)

print("✅ SHAP calculé")
print("Shape shap_values:", shap_values.shape)
print("Shape X_te_mat:", X_te_mat.shape)

"""## 18. Natural-language explanations (French)

Per-row template that converts top-3 SHAP contributors into a French sentence. Suitable for embedding in API responses.
"""

# ============================================================
# 18. Natural-language explanations in French
# ============================================================

FEATURE_LABELS_FR = {
    "frequence_bodacc": ("fréquence d'annonces BODACC", "élevée", "faible"),
    "nb_annonces_bodacc": ("volume d'annonces BODACC", "élevé", "faible"),
    "frequence_observations": ("fréquence d'observations", "élevée", "faible"),
    "frequence_observations_critiques": ("fréquence d'observations critiques", "élevée", "faible"),
    "nb_observations": ("observations administratives", "nombreuses", "rares"),
    "nb_observations_critiques": ("observations critiques", "nombreuses", "rares"),
    "has_alerte_juridique": ("alerte juridique", "présente", "absente"),

    "nb_etab_fermes": ("établissements fermés", "nombreux", "peu nombreux"),
    "ratio_etab_fermes": ("ratio d'établissements fermés", "élevé", "faible"),
    "a_ferme_etablissement": ("fermeture d'établissement", "observée", "non observée"),

    "log_capital": ("capital social", "faible", "solide"),
    "log_capital_safe": ("capital social", "faible", "solide"),
    "capital_sur_actif": ("capital rapporté à l'actif", "faible", "correct"),
    "capital_tres_faible": ("capital très faible", "oui", "non"),
    "capital_symbolique": ("capital symbolique", "oui", "non"),
    "capital_absent": ("capital absent", "oui", "non"),

    "fragilite_financiere": ("fragilité financière", "présente", "absente"),
    "fragilite_financiere_sans_alerte": ("fragilité financière sans alerte juridique", "présente", "absente"),
    "bilan_capitaux_negatifs": ("capitaux propres négatifs", "oui", "non"),
    "bilan_resultat_negatif": ("résultat net négatif", "oui", "non"),
    "marge_nette_negative": ("marge nette négative", "oui", "non"),
    "marge_nette_faible": ("marge nette faible", "oui", "non"),
    "rentabilite_resultat_sur_ca": ("rentabilité", "faible", "correcte"),
    "solidite_capitaux_sur_actif": ("solidité financière", "faible", "correcte"),

    "profil_silencieux": ("profil silencieux", "oui", "non"),
    "silencieux_mais_fragile": ("profil silencieux mais fragile", "oui", "non"),
    "jeune_silencieuse_fragile": ("jeune entreprise silencieuse fragile", "oui", "non"),
    "ancienne_silencieuse_fragile": ("ancienne entreprise silencieuse fragile", "oui", "non"),

    "ratio_observations_critiques": ("part d'observations critiques", "élevée", "faible"),
    "depot_non_respecte": ("non-respect des obligations de dépôt", "oui", "non"),
    "secteur_risque_eleve": ("secteur à risque", "oui", "non"),
    "secteur_x_financier": ("cumul secteur et fragilité financière", "défavorable", "favorable"),
    "bodacc_x_financier": ("cumul BODACC et fragilité financière", "défavorable", "favorable"),
    "juridique_x_financier": ("cumul juridique et financier", "défavorable", "favorable"),

    "departement": ("département", "à risque", "standard"),
    "secteur_naf2": ("secteur NAF", "à risque", "standard"),
    "forme_juridique_lib": ("forme juridique", "à risque", "standard"),
    "forme_juridique_risque": ("classe de risque de la forme juridique", "élevée", "standard"),
    "stade_vie": ("stade de vie", "critique", "stable"),
}


def explain_row_fr(shap_row, feature_names, top_k=3, threshold_pos=0.05):
    positive_factors = sorted(
        [
            (name, float(value))
            for name, value in zip(feature_names, shap_row)
            if value > threshold_pos
        ],
        key=lambda x: -x[1],
    )[:top_k]

    if not positive_factors:
        return "Profil de risque conforme à la moyenne du portefeuille."

    parts = []

    for name, _ in positive_factors:
        label, high, _low = FEATURE_LABELS_FR.get(
            name,
            (name, "défavorable", "favorable")
        )
        parts.append(f"{label} {high}")

    return "Risque élevé : " + ", ".join(parts) + "."


if "shap_values" in globals() and shap_values is not None:
    df_te_with_pred = df_te_with_pred.reset_index(drop=True)

    sample_idx = (
        df_te_with_pred
        .sort_values("proba", ascending=False)
        .head(5)
        .index
        .tolist()
    )

    for i in sample_idx:
        proba = float(df_te_with_pred.loc[i, "proba"])
        actual = "cessée" if df_te_with_pred.loc[i, "target"] == 1 else "active"

        explanation = explain_row_fr(
            shap_values[i],
            feature_names,
            top_k=3,
            threshold_pos=0.05
        )

        if "denomination" in df_te_with_pred.columns:
            denom = df_te_with_pred.loc[i, "denomination"]
        elif "siren" in df_te_with_pred.columns:
            denom = df_te_with_pred.loc[i, "siren"]
        else:
            denom = f"row_{i}"

        print(f"[{denom}] proba={proba:.3f} | actual={actual}")
        print(f"  → {explanation}\n")
else:
    print("⚠️ SHAP non disponible. Exécute d'abord la cellule 17.")
def generate_explanation(row, shap_values_row, feature_names):
    contributions = list(zip(feature_names, shap_values_row))
    contributions = sorted(contributions, key=lambda x: abs(x[1]), reverse=True)[:3]

    explanation = "Risque élevé car : "

    for feat, val in contributions:
        explanation += f"{feat} ({val:.2f}), "

    return explanation[:-2]

"""## 19. Risk band assignment"""

# ============================================================
# 19. Risk band assignment
# ============================================================

def risk_band(p):
    if p < 0.10:
        return "very_low"
    if p < 0.30:
        return "low"
    if p < 0.55:
        return "medium"
    if p < 0.80:
        return "high"
    return "critical"


def risk_band_fr(category):
    mapping = {
        "very_low": "Très faible risque",
        "low": "Faible risque",
        "medium": "Risque modéré",
        "high": "Risque élevé",
        "critical": "Risque critique",
    }
    return mapping.get(category, category)


df_te_with_pred = df_te_with_pred.reset_index(drop=True)

df_te_with_pred["proba"] = proba_te_final
df_te_with_pred["predicted"] = y_te_pred
df_te_with_pred["risk_score"] = (proba_te_final * 100).round(1)
df_te_with_pred["risk_category"] = [risk_band(p) for p in proba_te_final]
df_te_with_pred["risk_category_fr"] = [
    risk_band_fr(cat) for cat in df_te_with_pred["risk_category"]
]

df_te_with_pred["confidence_score"] = (
    np.maximum(proba_te_final, 1 - proba_te_final) * 100
).round(1)

if "shap_values" in globals() and shap_values is not None:
    df_te_with_pred["explanation_fr"] = [
        explain_row_fr(
            shap_values[i],
            feature_names,
            top_k=3,
            threshold_pos=0.05
        )
        for i in range(len(df_te_with_pred))
    ]
else:
    df_te_with_pred["explanation_fr"] = "Explication SHAP non disponible."

print("Risk category distribution (test set):")
print(df_te_with_pred["risk_category_fr"].value_counts())

print("\nAperçu:")
display(df_te_with_pred[[
    "target",
    "predicted",
    "proba",
    "risk_score",
    "risk_category_fr",
    "confidence_score",
    "explanation_fr"
]].head(10))

"""## 20. Export everything to Drive"""

# ============================================================
# 20. Export everything to Drive — CORRIGÉ
# ============================================================

out = Path(OUTPUT_DIR)
out.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------
metrics_path = out / f"metrics_comparison_{RUN_TAG}.csv"
thresholds_path = out / f"thresholds_{RUN_TAG}.csv"
predictions_path = out / f"predictions_test_{RUN_TAG}.csv"
fn_path = out / f"false_negatives_{RUN_TAG}.csv"
perm_path = out / f"permutation_importance_{RUN_TAG}.csv"
model_path = out / f"model_{winner}_raw_{RUN_TAG}.pkl"
metadata_path = out / f"run_metadata_{RUN_TAG}.json"

# ------------------------------------------------------------
# 2. Export metrics + thresholds
# ------------------------------------------------------------
metrics_df.to_csv(metrics_path, index=False)
thr_df.to_csv(thresholds_path, index=False)

# ------------------------------------------------------------
# 3. Export predictions
# ------------------------------------------------------------
id_cols = [
    c for c in [
        "siren",
        "denomination",
        "departement",
        "secteur_naf2",
        "forme_juridique_lib"
    ]
    if c in df_te_with_pred.columns
]

pred_cols = id_cols + [
    "observation_date",
    "target",
    "predicted",
    "proba",
    "risk_score",
    "risk_category",
    "risk_category_fr",
    "confidence_score",
    "explanation_fr"
]

pred_cols = [c for c in pred_cols if c in df_te_with_pred.columns]

df_te_with_pred[pred_cols].to_csv(predictions_path, index=False)

# ------------------------------------------------------------
# 4. Export false negatives + permutation importance
# ------------------------------------------------------------
if "df_fn" in globals():
    df_fn.to_csv(fn_path, index=False)
else:
    pd.DataFrame().to_csv(fn_path, index=False)

if "perm_df" in globals():
    perm_df.to_csv(perm_path, index=False)
else:
    pd.DataFrame().to_csv(perm_path, index=False)

# ------------------------------------------------------------
# 5. Export model bundle
# ------------------------------------------------------------
with open(model_path, "wb") as fh:
    pickle.dump(
        {
            "preprocessor": win["preprocessor"],
            "model": win["model"],
            "numeric_features": win["numeric_features"],
            "categorical_features": win["categorical_features"],
            "feature_names_out": win["feature_names_out"],
            "final_threshold": FINAL_THRESHOLD,
            "winner": winner,
            "use_calibration": False,
            "score_source": "raw_probability",
        },
        fh
    )

# ------------------------------------------------------------
# 6. Export SHAP sample
# ------------------------------------------------------------
if "shap_values" in globals() and shap_values is not None:
    shap_sample_path = out / f"shap_values_sample_{RUN_TAG}.npy"
    np.save(shap_sample_path, shap_values[:1000])
else:
    shap_sample_path = None

# ------------------------------------------------------------
# 7. Metadata corrigé
# ------------------------------------------------------------
metadata = {
    "run_tag": RUN_TAG,
    "reference_date": REFERENCE_DATE.isoformat(),
    "test_cutoff": TEST_CUTOFF.isoformat(),
    "random_state": RANDOM_STATE,
    "min_recall": MIN_RECALL,
    "cost_fn": COST_FN,
    "cost_fp": COST_FP,
    "leaky_features": LEAKY_FEATURES,
    "numeric_features_audit": NUMERIC_FEATURES_AUDIT,
    "categorical_features": CATEGORICAL_FEATURES,
    "winner": winner,
    "use_calibration": False,
    "score_source": "raw_probability",
    "final_threshold": float(FINAL_THRESHOLD),

    # Correction : thr_recall et thr_cost supprimés
    "thresholds_evaluated": {
        "selected_threshold": float(FINAL_THRESHOLD),
    },

    "n_train": int(len(df_tr)),
    "n_val": int(len(df_va)),
    "n_test": int(len(df_test)),
    "n_test_cessees": int((df_test["target"] == 1).sum()),
    "n_test_actives": int((df_test["target"] == 0).sum()),

    "final_metrics": {
        "roc_auc": float(roc_auc_score(y_te, proba_te_final)),
        "pr_auc": float(average_precision_score(y_te, proba_te_final)),
        "brier": float(brier_score_loss(y_te, proba_te_final)),
        "precision": float(precision_score(y_te, y_te_pred, zero_division=0)),
        "recall": float(recall_score(y_te, y_te_pred, zero_division=0)),
        "f1": float(f1_score(y_te, y_te_pred, zero_division=0)),
    },
}

with open(metadata_path, "w", encoding="utf-8") as fh:
    json.dump(metadata, fh, indent=2, ensure_ascii=False)

# ------------------------------------------------------------
# 8. Summary
# ------------------------------------------------------------
print("✅ Files written to:", OUTPUT_DIR)
print(" -", metrics_path.name)
print(" -", thresholds_path.name)
print(" -", predictions_path.name)
print(" -", fn_path.name)
print(" -", perm_path.name)
print(" -", model_path.name)
print(" -", metadata_path.name)

if shap_sample_path is not None:
    print(" -", shap_sample_path.name)

"""## 21. Summary

**What this notebook validates:**

1. **Leakage audit** — section 12 trains every model with and without 5 suspect features. The `pr_auc_delta_baseline_minus_audit` row tells you how much of your 0.925 PR-AUC was real signal vs leaked label.
2. **Honest comparison** — XGBoost, LightGBM, CatBoost on the same temporal split, same preprocessing, same imbalance handling. The winner is picked on AUDIT test PR-AUC, not on the inflated baseline.
3. **Calibration** — isotonic on validation, before any thresholding. Calibration plot in section 13 shows whether `risk_score = proba × 100` is meaningful.
4. **Two threshold strategies** — your existing recall-constrained rule and a cost-sensitive alternative. Section 14 shows both side-by-side so you can pick on evidence.
5. **Error analysis & explanations** — section 16 surfaces failure modes; section 18 produces French sentences ready for the API output.

**Next steps if PR-AUC drops sharply in the audit:**
- Add date-windowed BODACC aggregations (events with `date < observation_date` only)
- Replace `departement` with smoothed target encoding (kills the cardinality bias in feature importance)
- Walk-forward validation across 2021/2022/2023 cutoffs to estimate generalization variance
"""